export const categories = [
  { slug: "mat",       name: "Mat & Godis",       icon: "🍖" },
  { slug: "sand",      name: "Kattlåda & Sand",   icon: "🪨" },
  { slug: "mobler",    name: "Möbler & Klösträd", icon: "🛋️" },
  { slug: "tillbehor", name: "Tillbehör",         icon: "✨" },
];

export const products = [
  {
    id: 200,
    slug: "applaws-katt-multipack-fisk-urval-12x156g-200",
    name: "Applaws katt Multipack fisk urval 12x156g",
    brand: "Applaws",
    category: "mat",
    price: 300,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/5060481899086.png",
    placeholder: "🍖",
    weight: "1,872 kg",
    rating: 4.6,
    reviews: 96,
    badge: "Bästsäljare",
    description: "Premium från Applaws. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "9113575-WOK",
  },
  {
    id: 201,
    slug: "applaws-katt-multipack-fisk-urval-i-gel-12x70g-201",
    name: "Applaws katt Multipack fisk urval i gelé 12x70g",
    brand: "Applaws",
    category: "mat",
    price: 150,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/5060481899147.png",
    placeholder: "🍖",
    weight: "0,84 kg",
    rating: 4.7,
    reviews: 44,
    badge: null,
    description: "Premium från Applaws. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "9113588-WOK",
  },
  {
    id: 202,
    slug: "granatapet-delikatesser-pase-kalkon-fasan-85-g-202",
    name: "GranataPet delikatesser påse kalkon & fasan 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197724_delicatessen_85g_pouch_truthahn_fasan.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 3.9,
    reviews: 28,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197724-GP",
  },
  {
    id: 203,
    slug: "wolfsblut-burk-blue-mountain-395g-203",
    name: "Wolfsblut burk Blue Mountain 395g",
    brand: "Wolfsblut",
    category: "mat",
    price: 35,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wb783748wolfsblutadultbluemountain-wildmitkartoffelnnassfutter6x395g.jpg",
    placeholder: "🍖",
    weight: "0,395 kg",
    rating: 4.3,
    reviews: 31,
    badge: "Nyhet",
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB783748",
  },
  {
    id: 204,
    slug: "wolfsblut-vuxen-vilt-duck-turkey-800g-204",
    name: "Wolfsblut vuxen vilt Duck & Turkey 800g",
    brand: "Wolfsblut",
    category: "mat",
    price: 60,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wb784523wolfsblutadultwildduckturkeynassfutter6x800g.png",
    placeholder: "🍖",
    weight: "0,8 kg",
    rating: 4.1,
    reviews: 102,
    badge: null,
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB784523",
  },
  {
    id: 205,
    slug: "wolfsblut-burk-vilt-duck-puppy-395g-205",
    name: "Wolfsblut burk vilt Duck Puppy 395g",
    brand: "Wolfsblut",
    category: "mat",
    price: 35,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wb783090wolfsblutpuppywildduck-entemitkrbisnassfutter6x395g.jpg",
    placeholder: "🍖",
    weight: "0,395 kg",
    rating: 4.3,
    reviews: 159,
    badge: null,
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB783090",
  },
  {
    id: 206,
    slug: "granatapet-delikatesser-pase-lax-ren-85-g-206",
    name: "GranataPet delikatesser påse lax ren 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197762_delicatessen_85g_pouch_lachs_pur.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.3,
    reviews: 65,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197762-GP",
  },
  {
    id: 207,
    slug: "granatapet-delikatesser-pase-kalv-ren-85-g-207",
    name: "GranataPet delikatesser påse kalv ren 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197809_delicatessen_85g_pouch_kalb_pur.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 3.9,
    reviews: 116,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197809-GP",
  },
  {
    id: 208,
    slug: "granatapet-delikatesser-pase-lax-kalkon-85-g-208",
    name: "GranataPet delikatesser påse lax & kalkon 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197601_delicatessen_85g_pouch_lachs_pute.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.8,
    reviews: 56,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197601-GP",
  },
  {
    id: 209,
    slug: "granatapet-delikatesser-burk-kattunge-fjaderfa-200g-209",
    name: "GranataPet delikatesser burk kattunge fjäderfä 200g",
    brand: "GranataPet",
    category: "mat",
    price: 25,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/198127_delicatessen_2019_200g_3d_kitten.jpg",
    placeholder: "🍖",
    weight: "0,2 kg",
    rating: 4.2,
    reviews: 103,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "198127-GP",
  },
  {
    id: 210,
    slug: "granatapet-delikatesser-pase-lamm-kalkon-85-g-210",
    name: "GranataPet delikatesser påse lamm & kalkon 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197663_delicatessen_85g_pouch_lamm_truthahn.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.1,
    reviews: 137,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197663-GP",
  },
  {
    id: 211,
    slug: "granatapet-delikatesser-pase-anka-fjaderfa-85-g-211",
    name: "GranataPet delikatesser påse anka & fjäderfä 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197649_delicatessen_85g_pouch_ente_gefluegel.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.3,
    reviews: 132,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197649-GP",
  },
  {
    id: 212,
    slug: "wolfsblut-burk-vilt-duck-turkey-puppy-395g-212",
    name: "Wolfsblut burk vilt Duck & Turkey Puppy 395g",
    brand: "Wolfsblut",
    category: "mat",
    price: 35,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wb784486wolfsblutpuppywildduckturkeynassfutter6x395g.jpg",
    placeholder: "🍖",
    weight: "0,395 kg",
    rating: 4.1,
    reviews: 24,
    badge: null,
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB784486",
  },
  {
    id: 213,
    slug: "granatapet-delikatesser-pase-vilt-ren-85-g-213",
    name: "GranataPet delikatesser påse vilt ren 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197748_delicatessen_85g_pouch_wild_pur.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.2,
    reviews: 125,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197748-GP",
  },
  {
    id: 214,
    slug: "wolfsblut-burk-vilt-duck-800g-214",
    name: "Wolfsblut burk vilt Duck 800g",
    brand: "Wolfsblut",
    category: "mat",
    price: 65,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wb783069wolfsblutadultwildduck-entemitkartoffelnnassfutter6x800g.jpg",
    placeholder: "🍖",
    weight: "0,8 kg",
    rating: 4.7,
    reviews: 98,
    badge: null,
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB783069",
  },
  {
    id: 215,
    slug: "granatapet-delikatesser-pase-vilt-tonfisk-85-g-215",
    name: "GranataPet delikatesser påse vilt & tonfisk 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197540_delicatessen_85g_pouch_wild_thunfisch.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.4,
    reviews: 154,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197540-GP",
  },
  {
    id: 216,
    slug: "granatapet-delikatesser-pase-kalkon-rakor-85-g-216",
    name: "GranataPet delikatesser påse kalkon & räkor 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197564_delicatessen_85g_pouch_pute_shrimps.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.6,
    reviews: 55,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197564-GP",
  },
  {
    id: 217,
    slug: "granatapet-delikatesser-pase-tonfisk-anka-85-g-217",
    name: "GranataPet delikatesser påse tonfisk & anka 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197625_delicatessen_85g_pouch_thunfisch_ente.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.7,
    reviews: 163,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197625-GP",
  },
  {
    id: 218,
    slug: "granatapet-delikatesser-pase-kyckling-ren-85-g-218",
    name: "GranataPet delikatesser påse kyckling ren 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197786_delicatessen_85g_pouch_huhn_pur.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.5,
    reviews: 115,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197786-GP",
  },
  {
    id: 219,
    slug: "granatapet-delikatesser-pase-kattunge-fjaderfa-85-g-219",
    name: "GranataPet delikatesser påse kattunge fjäderfä 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197823_delicatessen_85g_pouch_kitten_junior.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.7,
    reviews: 113,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197823-GP",
  },
  {
    id: 220,
    slug: "granatapet-delikatesser-pase-lax-meeresfruchte-85-g-220",
    name: "GranataPet delikatesser påse lax & Meeresfrüchte 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197687_delicatessen_85g_pouch_lachs_meeresfruechte.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.2,
    reviews: 161,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197687-GP",
  },
  {
    id: 221,
    slug: "granatapet-delikatesser-pase-fasan-kanin-85-g-221",
    name: "GranataPet delikatesser påse fasan & kanin 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197588_delicatessen_85g_pouch_fasan_kaninchen.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.8,
    reviews: 83,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197588-GP",
  },
  {
    id: 222,
    slug: "granatapet-delikatesser-pase-kalv-kanin-85-g-222",
    name: "GranataPet delikatesser påse kalv & kanin 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197700_delicatessen_85g_pouch_kalb_kaninchen.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.6,
    reviews: 38,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197700-GP",
  },
  {
    id: 223,
    slug: "wolfsblut-burk-dark-forest-800g-223",
    name: "Wolfsblut burk Dark Forest 800g",
    brand: "Wolfsblut",
    category: "mat",
    price: 65,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wb783342darkforestadult-wildmitskartoffel6x800g.jpg",
    placeholder: "🍖",
    weight: "0,8 kg",
    rating: 4.7,
    reviews: 50,
    badge: null,
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB783342",
  },
  {
    id: 224,
    slug: "wolfsblut-burk-black-bird-800g-224",
    name: "Wolfsblut burk Black Bird 800g",
    brand: "Wolfsblut",
    category: "mat",
    price: 65,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wb783427wolfsblutadultblackbird-truthahnmitskartoffelnnassfutter6x800g.jpg",
    placeholder: "🍖",
    weight: "0,8 kg",
    rating: 4.1,
    reviews: 99,
    badge: null,
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB783427",
  },
  {
    id: 225,
    slug: "wolfsblut-vetline-weight-management-2-kg-225",
    name: "Wolfsblut VetLine Weight Management - 2 kg",
    brand: "Wolfsblut",
    category: "mat",
    price: 190,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wolfsblut_trockenfutter_weight_management_frontside_2kg_4260603786442_1000px_1.jpg",
    placeholder: "🌾",
    weight: "2 kg",
    rating: 4.7,
    reviews: 137,
    badge: "Populär",
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB786442",
  },
  {
    id: 226,
    slug: "wolfsblut-vetline-weight-management-12-kg-226",
    name: "Wolfsblut VetLine Weight Management - 12 kg",
    brand: "Wolfsblut",
    category: "mat",
    price: 840,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wb786459wolfsblutvetlineweightmanagement12kg.jpg",
    placeholder: "🌾",
    weight: "12 kg",
    rating: 4.1,
    reviews: 61,
    badge: null,
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB786459",
  },
  {
    id: 227,
    slug: "granatapet-delikatesser-kattunge-fjaderfa-300-g-227",
    name: "GranataPet delikatesser kattunge fjäderfä - 300 g",
    brand: "GranataPet",
    category: "mat",
    price: 45,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197489_197502_delicatessen_kitten_junior.jpg",
    placeholder: "🌾",
    weight: "0,3 kg",
    rating: 4.8,
    reviews: 126,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197489-GP",
  },
  {
    id: 228,
    slug: "granatapet-delikatesser-kattunge-fjaderfa-1-8-kg-228",
    name: "GranataPet delikatesser kattunge fjäderfä - 1,8 kg",
    brand: "GranataPet",
    category: "mat",
    price: 185,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197489_197502_delicatessen_kitten_junior.jpg",
    placeholder: "🌾",
    weight: "1,8 kg",
    rating: 4.7,
    reviews: 103,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197502-GP",
  },
  {
    id: 229,
    slug: "granatapet-delikatesser-kattunge-fjaderfa-9-kg-229",
    name: "GranataPet delikatesser kattunge fjäderfä - 9 kg",
    brand: "GranataPet",
    category: "mat",
    price: 640,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197489_197502_delicatessen_kitten_junior.jpg",
    placeholder: "🌾",
    weight: "9 kg",
    rating: 4.1,
    reviews: 67,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197526-GP",
  },
  {
    id: 230,
    slug: "wolfsblut-black-bird-puppy-large-12-5-kg-230",
    name: "Wolfsblut Black Bird Puppy Large - 12,5 kg",
    brand: "Wolfsblut",
    category: "mat",
    price: 930,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4260262761828.jpg",
    placeholder: "🌾",
    weight: "12,5 kg",
    rating: 4.2,
    reviews: 89,
    badge: null,
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB784769",
  },
  {
    id: 231,
    slug: "granatapet-delikatesser-rakor-vuxen-300-g-231",
    name: "GranataPet delikatesser räkor vuxen - 300 g",
    brand: "GranataPet",
    category: "mat",
    price: 45,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197243_197267_delicatessen_shrimps.jpg",
    placeholder: "🌾",
    weight: "0,3 kg",
    rating: 4.1,
    reviews: 71,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197243-GP",
  },
  {
    id: 232,
    slug: "granatapet-delikatesser-rakor-vuxen-9-kg-232",
    name: "GranataPet delikatesser räkor vuxen - 9 kg",
    brand: "GranataPet",
    category: "mat",
    price: 640,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197243_197267_delicatessen_shrimps.jpg",
    placeholder: "🌾",
    weight: "9 kg",
    rating: 4.5,
    reviews: 43,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197281-GP",
  },
  {
    id: 233,
    slug: "granatapet-delikatesser-rakor-vuxen-1-8-kg-233",
    name: "GranataPet delikatesser räkor vuxen - 1,8 kg",
    brand: "GranataPet",
    category: "mat",
    price: 185,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197243_197267_delicatessen_shrimps.jpg",
    placeholder: "🌾",
    weight: "1,8 kg",
    rating: 4.5,
    reviews: 83,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197267-GP",
  },
  {
    id: 234,
    slug: "wolfsblut-vuxen-country-chicken-2-kg-234",
    name: "Wolfsblut vuxen Country Chicken - 2 kg",
    brand: "Wolfsblut",
    category: "mat",
    price: 200,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wb785063wolfsblutcountrychickenadult2kg.jpg",
    placeholder: "🌾",
    weight: "2 kg",
    rating: 4.2,
    reviews: 79,
    badge: null,
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB785063",
  },
  {
    id: 235,
    slug: "katzentoilette-furba-235",
    name: "Katzentoilette FURBA",
    brand: "Karlie",
    category: "sand",
    price: 190,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/84300a_z1.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.2,
    reviews: 104,
    badge: "Bästsäljare",
    description: "Premium från Karlie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "08334",
  },
  {
    id: 236,
    slug: "karlie-katzentoiletten-beutel-10er-set-236",
    name: "Karlie Katzentoiletten-Beutel - 10er Set",
    brand: "Karlie",
    category: "sand",
    price: 30,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/84303_z1.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.1,
    reviews: 88,
    badge: null,
    description: "Premium från Karlie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "84303",
  },
  {
    id: 237,
    slug: "karlie-universal-aktivkohlefilter-237",
    name: "Karlie Universal-Aktivkohlefilter",
    brand: "Karlie",
    category: "sand",
    price: 25,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/08309_z1.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.3,
    reviews: 128,
    badge: null,
    description: "Premium från Karlie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "08309",
  },
  {
    id: 238,
    slug: "karlie-swifty-scoop-n-clever-kotschaufel-med-tutenspend-238",
    name: "Karlie Swifty Scoop'n Clever Kotschaufel med Tütenspender",
    brand: "Karlie",
    category: "sand",
    price: 35,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/47938-impn.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.6,
    reviews: 156,
    badge: null,
    description: "Premium från Karlie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "47938-IMP",
  },
  {
    id: 239,
    slug: "karlie-swifty-scoop-metall-kotschaufel-239",
    name: "Karlie Swifty Scoop Metall-Kotschaufel",
    brand: "Karlie",
    category: "sand",
    price: 45,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/08385.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.3,
    reviews: 153,
    badge: null,
    description: "Premium från Karlie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "08385-IMP",
  },
  {
    id: 240,
    slug: "karlie-katzentoilette-med-rand-240",
    name: "Karlie Katzentoilette med Rand",
    brand: "Karlie",
    category: "sand",
    price: 50,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/karlie08312_z1.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.2,
    reviews: 125,
    badge: null,
    description: "Premium från Karlie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "08312",
  },
  {
    id: 241,
    slug: "karlie-percato-premium-katzenstreu-5-l-241",
    name: "Karlie PERCATO Premium Katzenstreu - 5 L",
    brand: "Karlie",
    category: "sand",
    price: 60,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/46880_z1.jpg",
    placeholder: "🪨",
    weight: "5 Liter",
    rating: 4.4,
    reviews: 151,
    badge: null,
    description: "Premium från Karlie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "46880",
  },
  {
    id: 242,
    slug: "karlie-percato-premium-katzenstreu-10-l-vorratsbeutel-242",
    name: "Karlie PERCATO Premium Katzenstreu - 10 L Vorratsbeutel",
    brand: "Karlie",
    category: "sand",
    price: 130,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/46881_z1.jpg",
    placeholder: "🪨",
    weight: "10 Liter",
    rating: 4.3,
    reviews: 92,
    badge: null,
    description: "Premium från Karlie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "46883",
  },
  {
    id: 243,
    slug: "trixie-junior-katzentoilette-kitty-243",
    name: "Trixie Junior Katzentoilette Kitty",
    brand: "Trixie",
    category: "sand",
    price: 40,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/kitty1.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.8,
    reviews: 91,
    badge: null,
    description: "Premium från Trixie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "4042-TRXI",
  },
  {
    id: 244,
    slug: "karlie-swifty-scoop-alu-kotschaufel-244",
    name: "Karlie Swifty Scoop Alu-Kotschaufel",
    brand: "Karlie",
    category: "sand",
    price: 140,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/low_jpg-08384.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.4,
    reviews: 122,
    badge: null,
    description: "Premium från Karlie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "08384",
  },
  {
    id: 245,
    slug: "karlie-flamingo-katzentoilette-graffiti-245",
    name: "Karlie Flamingo Katzentoilette Graffiti",
    brand: "Karlie",
    category: "sand",
    price: 115,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/560142.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.8,
    reviews: 160,
    badge: null,
    description: "Premium från Karlie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "560142",
  },
  {
    id: 246,
    slug: "trixie-be-eco-katzentoilette-vico-246",
    name: "Trixie Be Eco Katzentoilette Vico",
    brand: "Trixie",
    category: "sand",
    price: 135,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/40210-trxi.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4,
    reviews: 77,
    badge: null,
    description: "Premium från Trixie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "40210-TRXI",
  },
  {
    id: 247,
    slug: "trixie-katzentoilette-delio-med-motiv-grun-wei-247",
    name: "Trixie Katzentoilette Delio med Motiv - grün/weiß",
    brand: "Trixie",
    category: "sand",
    price: 130,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/40398.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.3,
    reviews: 32,
    badge: null,
    description: "Premium från Trixie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "40398-TRXI",
  },
  {
    id: 248,
    slug: "savic-katzentoilette-flach-blau-rosa-248",
    name: "Savic Katzentoilette flach - blau/rosa",
    brand: "Savic",
    category: "sand",
    price: 30,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/0216_0000_1.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.1,
    reviews: 34,
    badge: null,
    description: "Premium från Savic. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "002169-SLTE",
  },
  {
    id: 249,
    slug: "trixie-katzentoilette-carlo-1-grau-hellgrau-249",
    name: "Trixie Katzentoilette Carlo 1 - grau/hellgrau",
    brand: "Trixie",
    category: "sand",
    price: 55,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/40111-trxi-neu.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.5,
    reviews: 23,
    badge: null,
    description: "Premium från Trixie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "40111-TRXI",
  },
];

export function getProduct(slug) {
  return products.find(p => p.slug === slug) ?? null;
}

export function getByCategory(cat) {
  return products.filter(p => p.category === cat);
}
