export const categories = [
  { slug: "mat",       name: "Mat & Godis",       icon: "🍖" },
  { slug: "sand",      name: "Kattlåda & Sand",   icon: "🪨" },
  { slug: "mobler",    name: "Möbler & Klösträd", icon: "🛋️" },
  { slug: "tillbehor", name: "Tillbehör",         icon: "✨" },
];

export const products = [
  {
    id: 200,
    slug: "applaws-katt-multipack-fisk-urval-12x156g-200",
    name: "Applaws katt Multipack fisk urval 12x156g",
    brand: "Applaws",
    category: "mat",
    price: 300,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/5060481899086.png",
    placeholder: "🍖",
    weight: "1,872 kg",
    rating: 4.6,
    reviews: 96,
    badge: "Bästsäljare",
    description: "Premium från Applaws. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "9113575-WOK",
  },
  {
    id: 201,
    slug: "applaws-katt-multipack-fisk-urval-i-gel-12x70g-201",
    name: "Applaws katt Multipack fisk urval i gelé 12x70g",
    brand: "Applaws",
    category: "mat",
    price: 150,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/5060481899147.png",
    placeholder: "🍖",
    weight: "0,84 kg",
    rating: 4.7,
    reviews: 44,
    badge: null,
    description: "Premium från Applaws. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "9113588-WOK",
  },
  {
    id: 202,
    slug: "granatapet-delikatesser-pase-kalkon-fasan-85-g-202",
    name: "GranataPet delikatesser påse kalkon & fasan 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197724_delicatessen_85g_pouch_truthahn_fasan.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 3.9,
    reviews: 28,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197724-GP",
  },
  {
    id: 203,
    slug: "wolfsblut-burk-blue-mountain-395g-203",
    name: "Wolfsblut burk Blue Mountain 395g",
    brand: "Wolfsblut",
    category: "mat",
    price: 35,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wb783748wolfsblutadultbluemountain-wildmitkartoffelnnassfutter6x395g.jpg",
    placeholder: "🍖",
    weight: "0,395 kg",
    rating: 4.3,
    reviews: 31,
    badge: "Nyhet",
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB783748",
  },
  {
    id: 204,
    slug: "wolfsblut-vuxen-vilt-duck-turkey-800g-204",
    name: "Wolfsblut vuxen vilt Duck & Turkey 800g",
    brand: "Wolfsblut",
    category: "mat",
    price: 60,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wb784523wolfsblutadultwildduckturkeynassfutter6x800g.png",
    placeholder: "🍖",
    weight: "0,8 kg",
    rating: 4.1,
    reviews: 102,
    badge: null,
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB784523",
  },
  {
    id: 205,
    slug: "wolfsblut-burk-vilt-duck-puppy-395g-205",
    name: "Wolfsblut burk vilt Duck Puppy 395g",
    brand: "Wolfsblut",
    category: "mat",
    price: 35,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wb783090wolfsblutpuppywildduck-entemitkrbisnassfutter6x395g.jpg",
    placeholder: "🍖",
    weight: "0,395 kg",
    rating: 4.3,
    reviews: 159,
    badge: null,
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB783090",
  },
  {
    id: 206,
    slug: "granatapet-delikatesser-pase-lax-ren-85-g-206",
    name: "GranataPet delikatesser påse lax ren 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197762_delicatessen_85g_pouch_lachs_pur.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.3,
    reviews: 65,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197762-GP",
  },
  {
    id: 207,
    slug: "granatapet-delikatesser-pase-kalv-ren-85-g-207",
    name: "GranataPet delikatesser påse kalv ren 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197809_delicatessen_85g_pouch_kalb_pur.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 3.9,
    reviews: 116,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197809-GP",
  },
  {
    id: 208,
    slug: "granatapet-delikatesser-pase-lax-kalkon-85-g-208",
    name: "GranataPet delikatesser påse lax & kalkon 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197601_delicatessen_85g_pouch_lachs_pute.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.8,
    reviews: 56,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197601-GP",
  },
  {
    id: 209,
    slug: "granatapet-delikatesser-burk-kattunge-fjaderfa-200g-209",
    name: "GranataPet delikatesser burk kattunge fjäderfä 200g",
    brand: "GranataPet",
    category: "mat",
    price: 25,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/198127_delicatessen_2019_200g_3d_kitten.jpg",
    placeholder: "🍖",
    weight: "0,2 kg",
    rating: 4.2,
    reviews: 103,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "198127-GP",
  },
  {
    id: 210,
    slug: "granatapet-delikatesser-pase-lamm-kalkon-85-g-210",
    name: "GranataPet delikatesser påse lamm & kalkon 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197663_delicatessen_85g_pouch_lamm_truthahn.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.1,
    reviews: 137,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197663-GP",
  },
  {
    id: 211,
    slug: "granatapet-delikatesser-pase-anka-fjaderfa-85-g-211",
    name: "GranataPet delikatesser påse anka & fjäderfä 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197649_delicatessen_85g_pouch_ente_gefluegel.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.3,
    reviews: 132,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197649-GP",
  },
  {
    id: 212,
    slug: "wolfsblut-burk-vilt-duck-turkey-puppy-395g-212",
    name: "Wolfsblut burk vilt Duck & Turkey Puppy 395g",
    brand: "Wolfsblut",
    category: "mat",
    price: 35,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wb784486wolfsblutpuppywildduckturkeynassfutter6x395g.jpg",
    placeholder: "🍖",
    weight: "0,395 kg",
    rating: 4.1,
    reviews: 24,
    badge: null,
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB784486",
  },
  {
    id: 213,
    slug: "granatapet-delikatesser-pase-vilt-ren-85-g-213",
    name: "GranataPet delikatesser påse vilt ren 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197748_delicatessen_85g_pouch_wild_pur.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.2,
    reviews: 125,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197748-GP",
  },
  {
    id: 214,
    slug: "wolfsblut-burk-vilt-duck-800g-214",
    name: "Wolfsblut burk vilt Duck 800g",
    brand: "Wolfsblut",
    category: "mat",
    price: 65,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wb783069wolfsblutadultwildduck-entemitkartoffelnnassfutter6x800g.jpg",
    placeholder: "🍖",
    weight: "0,8 kg",
    rating: 4.7,
    reviews: 98,
    badge: null,
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB783069",
  },
  {
    id: 215,
    slug: "granatapet-delikatesser-pase-vilt-tonfisk-85-g-215",
    name: "GranataPet delikatesser påse vilt & tonfisk 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197540_delicatessen_85g_pouch_wild_thunfisch.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.4,
    reviews: 154,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197540-GP",
  },
  {
    id: 216,
    slug: "granatapet-delikatesser-pase-kalkon-rakor-85-g-216",
    name: "GranataPet delikatesser påse kalkon & räkor 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197564_delicatessen_85g_pouch_pute_shrimps.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.6,
    reviews: 55,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197564-GP",
  },
  {
    id: 217,
    slug: "granatapet-delikatesser-pase-tonfisk-anka-85-g-217",
    name: "GranataPet delikatesser påse tonfisk & anka 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197625_delicatessen_85g_pouch_thunfisch_ente.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.7,
    reviews: 163,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197625-GP",
  },
  {
    id: 218,
    slug: "granatapet-delikatesser-pase-kyckling-ren-85-g-218",
    name: "GranataPet delikatesser påse kyckling ren 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197786_delicatessen_85g_pouch_huhn_pur.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.5,
    reviews: 115,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197786-GP",
  },
  {
    id: 219,
    slug: "granatapet-delikatesser-pase-kattunge-fjaderfa-85-g-219",
    name: "GranataPet delikatesser påse kattunge fjäderfä 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197823_delicatessen_85g_pouch_kitten_junior.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.7,
    reviews: 113,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197823-GP",
  },
  {
    id: 220,
    slug: "granatapet-delikatesser-pase-lax-meeresfruchte-85-g-220",
    name: "GranataPet delikatesser påse lax & Meeresfrüchte 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197687_delicatessen_85g_pouch_lachs_meeresfruechte.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.2,
    reviews: 161,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197687-GP",
  },
  {
    id: 221,
    slug: "granatapet-delikatesser-pase-fasan-kanin-85-g-221",
    name: "GranataPet delikatesser påse fasan & kanin 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197588_delicatessen_85g_pouch_fasan_kaninchen.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.8,
    reviews: 83,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197588-GP",
  },
  {
    id: 222,
    slug: "granatapet-delikatesser-pase-kalv-kanin-85-g-222",
    name: "GranataPet delikatesser påse kalv & kanin 85 g",
    brand: "GranataPet",
    category: "mat",
    price: 15,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197700_delicatessen_85g_pouch_kalb_kaninchen.jpg",
    placeholder: "🍖",
    weight: "0,085 kg",
    rating: 4.6,
    reviews: 38,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197700-GP",
  },
  {
    id: 223,
    slug: "wolfsblut-burk-dark-forest-800g-223",
    name: "Wolfsblut burk Dark Forest 800g",
    brand: "Wolfsblut",
    category: "mat",
    price: 65,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wb783342darkforestadult-wildmitskartoffel6x800g.jpg",
    placeholder: "🍖",
    weight: "0,8 kg",
    rating: 4.7,
    reviews: 50,
    badge: null,
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB783342",
  },
  {
    id: 224,
    slug: "wolfsblut-burk-black-bird-800g-224",
    name: "Wolfsblut burk Black Bird 800g",
    brand: "Wolfsblut",
    category: "mat",
    price: 65,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wb783427wolfsblutadultblackbird-truthahnmitskartoffelnnassfutter6x800g.jpg",
    placeholder: "🍖",
    weight: "0,8 kg",
    rating: 4.1,
    reviews: 99,
    badge: null,
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB783427",
  },
  {
    id: 225,
    slug: "wolfsblut-vetline-weight-management-2-kg-225",
    name: "Wolfsblut VetLine Weight Management - 2 kg",
    brand: "Wolfsblut",
    category: "mat",
    price: 190,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wolfsblut_trockenfutter_weight_management_frontside_2kg_4260603786442_1000px_1.jpg",
    placeholder: "🌾",
    weight: "2 kg",
    rating: 4.7,
    reviews: 137,
    badge: "Populär",
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB786442",
  },
  {
    id: 226,
    slug: "wolfsblut-vetline-weight-management-12-kg-226",
    name: "Wolfsblut VetLine Weight Management - 12 kg",
    brand: "Wolfsblut",
    category: "mat",
    price: 840,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wb786459wolfsblutvetlineweightmanagement12kg.jpg",
    placeholder: "🌾",
    weight: "12 kg",
    rating: 4.1,
    reviews: 61,
    badge: null,
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB786459",
  },
  {
    id: 227,
    slug: "granatapet-delikatesser-kattunge-fjaderfa-300-g-227",
    name: "GranataPet delikatesser kattunge fjäderfä - 300 g",
    brand: "GranataPet",
    category: "mat",
    price: 45,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197489_197502_delicatessen_kitten_junior.jpg",
    placeholder: "🌾",
    weight: "0,3 kg",
    rating: 4.8,
    reviews: 126,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197489-GP",
  },
  {
    id: 228,
    slug: "granatapet-delikatesser-kattunge-fjaderfa-1-8-kg-228",
    name: "GranataPet delikatesser kattunge fjäderfä - 1,8 kg",
    brand: "GranataPet",
    category: "mat",
    price: 185,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197489_197502_delicatessen_kitten_junior.jpg",
    placeholder: "🌾",
    weight: "1,8 kg",
    rating: 4.7,
    reviews: 103,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197502-GP",
  },
  {
    id: 229,
    slug: "granatapet-delikatesser-kattunge-fjaderfa-9-kg-229",
    name: "GranataPet delikatesser kattunge fjäderfä - 9 kg",
    brand: "GranataPet",
    category: "mat",
    price: 640,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197489_197502_delicatessen_kitten_junior.jpg",
    placeholder: "🌾",
    weight: "9 kg",
    rating: 4.1,
    reviews: 67,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197526-GP",
  },
  {
    id: 230,
    slug: "wolfsblut-black-bird-puppy-large-12-5-kg-230",
    name: "Wolfsblut Black Bird Puppy Large - 12,5 kg",
    brand: "Wolfsblut",
    category: "mat",
    price: 930,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4260262761828.jpg",
    placeholder: "🌾",
    weight: "12,5 kg",
    rating: 4.2,
    reviews: 89,
    badge: null,
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB784769",
  },
  {
    id: 231,
    slug: "granatapet-delikatesser-rakor-vuxen-300-g-231",
    name: "GranataPet delikatesser räkor vuxen - 300 g",
    brand: "GranataPet",
    category: "mat",
    price: 45,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197243_197267_delicatessen_shrimps.jpg",
    placeholder: "🌾",
    weight: "0,3 kg",
    rating: 4.1,
    reviews: 71,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197243-GP",
  },
  {
    id: 232,
    slug: "granatapet-delikatesser-rakor-vuxen-9-kg-232",
    name: "GranataPet delikatesser räkor vuxen - 9 kg",
    brand: "GranataPet",
    category: "mat",
    price: 640,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197243_197267_delicatessen_shrimps.jpg",
    placeholder: "🌾",
    weight: "9 kg",
    rating: 4.5,
    reviews: 43,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197281-GP",
  },
  {
    id: 233,
    slug: "granatapet-delikatesser-rakor-vuxen-1-8-kg-233",
    name: "GranataPet delikatesser räkor vuxen - 1,8 kg",
    brand: "GranataPet",
    category: "mat",
    price: 185,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/197243_197267_delicatessen_shrimps.jpg",
    placeholder: "🌾",
    weight: "1,8 kg",
    rating: 4.5,
    reviews: 83,
    badge: null,
    description: "Premium från GranataPet. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "197267-GP",
  },
  {
    id: 234,
    slug: "wolfsblut-vuxen-country-chicken-2-kg-234",
    name: "Wolfsblut vuxen Country Chicken - 2 kg",
    brand: "Wolfsblut",
    category: "mat",
    price: 200,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wb785063wolfsblutcountrychickenadult2kg.jpg",
    placeholder: "🌾",
    weight: "2 kg",
    rating: 4.2,
    reviews: 79,
    badge: null,
    description: "Premium från Wolfsblut. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "WB785063",
  },
  {
    id: 235,
    slug: "katzentoilette-furba-235",
    name: "Katzentoilette FURBA",
    brand: "Karlie",
    category: "sand",
    price: 190,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/84300a_z1.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.2,
    reviews: 104,
    badge: "Bästsäljare",
    description: "Premium från Karlie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "08334",
  },
  {
    id: 236,
    slug: "karlie-katzentoiletten-beutel-10er-set-236",
    name: "Karlie Katzentoiletten-Beutel - 10er Set",
    brand: "Karlie",
    category: "sand",
    price: 30,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/84303_z1.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.1,
    reviews: 88,
    badge: null,
    description: "Premium från Karlie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "84303",
  },
  {
    id: 237,
    slug: "karlie-universal-aktivkohlefilter-237",
    name: "Karlie Universal-Aktivkohlefilter",
    brand: "Karlie",
    category: "sand",
    price: 25,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/08309_z1.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.3,
    reviews: 128,
    badge: null,
    description: "Premium från Karlie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "08309",
  },
  {
    id: 238,
    slug: "karlie-swifty-scoop-n-clever-kotschaufel-med-tutenspend-238",
    name: "Karlie Swifty Scoop'n Clever Kotschaufel med Tütenspender",
    brand: "Karlie",
    category: "sand",
    price: 35,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/47938-impn.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.6,
    reviews: 156,
    badge: null,
    description: "Premium från Karlie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "47938-IMP",
  },
  {
    id: 239,
    slug: "karlie-swifty-scoop-metall-kotschaufel-239",
    name: "Karlie Swifty Scoop Metall-Kotschaufel",
    brand: "Karlie",
    category: "sand",
    price: 45,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/08385.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.3,
    reviews: 153,
    badge: null,
    description: "Premium från Karlie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "08385-IMP",
  },
  {
    id: 240,
    slug: "karlie-katzentoilette-med-rand-240",
    name: "Karlie Katzentoilette med Rand",
    brand: "Karlie",
    category: "sand",
    price: 50,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/karlie08312_z1.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.2,
    reviews: 125,
    badge: null,
    description: "Premium från Karlie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "08312",
  },
  {
    id: 241,
    slug: "karlie-percato-premium-katzenstreu-5-l-241",
    name: "Karlie PERCATO Premium Katzenstreu - 5 L",
    brand: "Karlie",
    category: "sand",
    price: 60,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/46880_z1.jpg",
    placeholder: "🪨",
    weight: "5 Liter",
    rating: 4.4,
    reviews: 151,
    badge: null,
    description: "Premium från Karlie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "46880",
  },
  {
    id: 242,
    slug: "karlie-percato-premium-katzenstreu-10-l-vorratsbeutel-242",
    name: "Karlie PERCATO Premium Katzenstreu - 10 L Vorratsbeutel",
    brand: "Karlie",
    category: "sand",
    price: 130,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/46881_z1.jpg",
    placeholder: "🪨",
    weight: "10 Liter",
    rating: 4.3,
    reviews: 92,
    badge: null,
    description: "Premium från Karlie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "46883",
  },
  {
    id: 243,
    slug: "trixie-junior-katzentoilette-kitty-243",
    name: "Trixie Junior Katzentoilette Kitty",
    brand: "Trixie",
    category: "sand",
    price: 40,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/kitty1.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.8,
    reviews: 91,
    badge: null,
    description: "Premium från Trixie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "4042-TRXI",
  },
  {
    id: 244,
    slug: "karlie-swifty-scoop-alu-kotschaufel-244",
    name: "Karlie Swifty Scoop Alu-Kotschaufel",
    brand: "Karlie",
    category: "sand",
    price: 140,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/low_jpg-08384.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.4,
    reviews: 122,
    badge: null,
    description: "Premium från Karlie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "08384",
  },
  {
    id: 245,
    slug: "karlie-flamingo-katzentoilette-graffiti-245",
    name: "Karlie Flamingo Katzentoilette Graffiti",
    brand: "Karlie",
    category: "sand",
    price: 115,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/560142.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.8,
    reviews: 160,
    badge: null,
    description: "Premium från Karlie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "560142",
  },
  {
    id: 246,
    slug: "trixie-be-eco-katzentoilette-vico-246",
    name: "Trixie Be Eco Katzentoilette Vico",
    brand: "Trixie",
    category: "sand",
    price: 135,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/40210-trxi.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4,
    reviews: 77,
    badge: null,
    description: "Premium från Trixie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "40210-TRXI",
  },
  {
    id: 247,
    slug: "trixie-katzentoilette-delio-med-motiv-grun-wei-247",
    name: "Trixie Katzentoilette Delio med Motiv - grün/weiß",
    brand: "Trixie",
    category: "sand",
    price: 130,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/40398.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.3,
    reviews: 32,
    badge: null,
    description: "Premium från Trixie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "40398-TRXI",
  },
  {
    id: 248,
    slug: "savic-katzentoilette-flach-blau-rosa-248",
    name: "Savic Katzentoilette flach - blau/rosa",
    brand: "Savic",
    category: "sand",
    price: 30,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/0216_0000_1.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.1,
    reviews: 34,
    badge: null,
    description: "Premium från Savic. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "002169-SLTE",
  },
  {
    id: 249,
    slug: "trixie-katzentoilette-carlo-1-grau-hellgrau-249",
    name: "Trixie Katzentoilette Carlo 1 - grau/hellgrau",
    brand: "Trixie",
    category: "sand",
    price: 55,
    originalPrice: null,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/40111-trxi-neu.jpg",
    placeholder: "🪨",
    weight: null,
    rating: 4.5,
    reviews: 23,
    badge: null,
    description: "Premium från Trixie. Utvalt för din katts välmående.",
    tags: [],
    inStock: true,
    articleNumber: "40111-TRXI",
  },
{ slug: "mat",       name: "Mat & Godis",       icon: "🍖" },
  { slug: "sand",      name: "Kattlåda & Sand",   icon: "🪨" },
  { slug: "mobler",    name: "Möbler & Klösträd", icon: "🛋️" },
  { slug: "tillbehor", name: "Tillbehör",         icon: "✨" },
];

export const products = [
  {
    id: 1,
    slug: "beeztees-beeztees-catrino-snackball-fur-katzen-1",
    name: "Beeztees Catrino snackboll för katter",
    brand: "Beeztees",
    category: "tillbehor",
    price: 40,
    originalPrice: 55,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/440432.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.3,
    reviews: 32,
    badge: null,
    description: "En rolig kattleksak i form av ett tankespel för din katt, detta är snackbollen Catrino från Beeztees. Kattmatsbollen stimulerar din katts sinnen. Med den justerbara öppningen kan du göra det lättare eller svårare för din katt att komma åt godsakerna och tappa slickarna",
    tags: [],
    inStock: true,
  },
{
    id: 2,
    slug: "karlie-karlie-big-mouse-katzenspa-40-cm-2",
    name: "Karlie BIG MOUSE kattkul - 40 cm",
    brand: "Karlie",
    category: "mobler",
    price: 215,
    originalPrice: 290,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/low_jpg-46385.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.3,
    reviews: 99,
    badge: null,
    description: "Extra tung mus att hänga på dörren eller väggen. Även idealisk som skrapleksak för mattor etc. Stor sisalskrapyta. Med kattmynta.",
    tags: [],
    inStock: true,
  },
{
    id: 3,
    slug: "karlie-karlie-bunte-fellmause-9er-set-3",
    name: "Karlie färgglada pälsmöss - set med 9 st",
    brand: "Karlie",
    category: "tillbehor",
    price: 80,
    originalPrice: 100,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/46018_z1.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.3,
    reviews: 101,
    badge: null,
    description: "- Med CATNIP-doft - Ca. 5 cm - Paket med 9: Grå, Röd, Gul - med skallereffekt",
    tags: [],
    inStock: true,
  },
{
    id: 4,
    slug: "karlie-karlie-plusch-spielmause-4er-set-4",
    name: "Karlie plyschmöss - set med 4 st",
    brand: "Karlie",
    category: "tillbehor",
    price: 30,
    originalPrice: 35,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4mause.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.3,
    reviews: 94,
    badge: null,
    description: "- Förpackning om 4 - 5 cm",
    tags: [],
    inStock: true,
  },
{
    id: 5,
    slug: "karlie-karlie-catnip-mause-4er-set-5",
    name: "Karlie CATNIP möss - set om 4",
    brand: "Karlie",
    category: "tillbehor",
    price: 30,
    originalPrice: 35,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/46518.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.3,
    reviews: 98,
    badge: null,
    description: "- Paket om 4 - Med CATNIP-doft - 5 cm",
    tags: [],
    inStock: true,
  },
{
    id: 6,
    slug: "karlie-karlie-deluxe-kratzbaum-banana-leaf-2-6",
    name: "Karlie Deluxe Cat Tree BANANBLAD 2",
    brand: "Karlie",
    category: "mobler",
    price: 1500,
    originalPrice: 1960,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/34891_z1.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.3,
    reviews: 78,
    badge: null,
    description: "Bananblad - ett återupptäckt naturmaterial. I många kulturer är detta material en integrerad del av det dagliga livet. Bananblad förkroppsligar naturen på ett unikt sätt. Formade av naturen blir löven massiva repmöbler, konstgjort handgjorda",
    tags: [],
    inStock: true,
  },
{
    id: 7,
    slug: "trixie-trixie-katzenhaus-cat-s-home-mit-balkon-7",
    name: "Trixie katthus Katthem med balkong",
    brand: "Trixie",
    category: "tillbehor",
    price: 825,
    originalPrice: 1035,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/44093_cats_home_mit_balkon_1.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.4,
    reviews: 239,
    badge: null,
    description: "för inomhus och utomhus gjorda av glaserat furuträ reträtt alternativ med balkong med trappsteg för att klättra upp till den övre nivån fötter skyddar mot markfukt och kyla och säkerställer god luftcirkulation under huset Färg: grå/vit Storlek: 45 × 65 × 45 cm",
    tags: [],
    inStock: true,
  },
{
    id: 8,
    slug: "karlie-karlie-katzenangel-igel-8",
    name: "Karlie Katzenangel Igelkott",
    brand: "Karlie",
    category: "tillbehor",
    price: 45,
    originalPrice: 60,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/low_jpg-46276_verp2.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.3,
    reviews: 77,
    badge: null,
    description: "Fantastiskt kattfiske med igelkott. Längd ca. 50 cm Olika färger. Tyvärr går det inte att välja färg då färgen är vald beroende på lager.",
    tags: [],
    inStock: true,
  },
{
    id: 9,
    slug: "karlie-karlie-katzen-futterschussel-aus-edelstahl-190-m",
    name: "Karlie Kattmatningsskål i rostfritt stål - 190ml",
    brand: "Karlie",
    category: "tillbehor",
    price: 20,
    originalPrice: 25,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/43053_z1.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.3,
    reviews: 94,
    badge: null,
    description: "- 11 cm diameter - 190ml - Tillverkad av rostfritt stål",
    tags: [],
    inStock: true,
  },
{
    id: 10,
    slug: "karlie-karlie-sisal-kratzbrett-fur-zimmerecken-50-x-24",
    name: "Karlie Sisal skrapbräda för rumshörn - 50 x 24 cm",
    brand: "Karlie",
    category: "mobler",
    price: 135,
    originalPrice: 200,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/46108_z1.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.3,
    reviews: 83,
    badge: null,
    description: "- Med CATNIP-doft - ca. 51 x 24 cm",
    tags: [],
    inStock: true,
  },
{
    id: 12,
    slug: "trixie-trixie-cat-activity-solitar-12",
    name: "Trixie Cat Activity Solitaire",
    brand: "Trixie",
    category: "tillbehor",
    price: 75,
    originalPrice: 110,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/catsolitaer.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.4,
    reviews: 242,
    badge: null,
    description: "Katter är väldigt lekfulla och nyfikna djur. De vill inte bara bli fysiskt engagerade och utmanade genom spel, utan också mentalt. Solitären består av en plastplatta med 7 täckkulor under vilka små godsaker gömmer sig. Med en liten tass",
    tags: [],
    inStock: true,
  },
{
    id: 16,
    slug: "trixie-trixie-crunch-pluschtunnel-60-cm-grau-16",
    name: "Trixie Crunch Plyschtunnel, 60 cm - Grå",
    brand: "Trixie",
    category: "tillbehor",
    price: 150,
    originalPrice: 220,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/42982.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.4,
    reviews: 257,
    badge: null,
    description: "Lektunneln gjord av mjuk plysch (polyester) erbjuder din katt eller valp en idealisk plats att dra sig tillbaka och koppla av. Samtidigt uppmuntrar den insydda prasslande folien till lek. Mått: ca. 22 x 60 cm (diameter x längd) Färg: Grå",
    tags: [],
    inStock: true,
  },
{
    id: 17,
    slug: "trixie-trixie-turning-feather-katzenspielzeug-17",
    name: "Trixie Turning Feather Cat Toy",
    brand: "Trixie",
    category: "tillbehor",
    price: 150,
    originalPrice: 220,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/46007.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.4,
    reviews: 247,
    badge: null,
    description: "Fjäder inuti virvlar runt, stannar och ändrar riktning oregelbundet Kan fyllas med små godsaker Automatisk avstängning efter ca. 15 minuter Halkfria gummifötter Batteridrivna (3 AA Mignon-batterier ingår ej) Plast Mått: ca. 22 cm Färg: grå",
    tags: [],
    inStock: true,
  },
{
    id: 20,
    slug: "trixie-trixie-pluschball-mit-bandern-20",
    name: "Trixie plyschboll med band",
    brand: "Trixie",
    category: "tillbehor",
    price: 10,
    originalPrice: 15,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4126-trxi.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.4,
    reviews: 253,
    badge: null,
    description: "Plyschbollen med band är utrustad med doft av klocka och kattmynta och är perfekt för jakt och lek. Storlek: ca. 4 cm 1 st Olika färger. Tyvärr går det inte att välja färg då färgen är vald beroende på lager.",
    tags: [],
    inStock: true,
  },
{
    id: 21,
    slug: "ebi-ebi-kratzbaum-bedford-127-schwarz-21",
    name: "EBI kattträd Bedford 127 - svart",
    brand: "EBI",
    category: "mobler",
    price: 1875,
    originalPrice: 2490,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/431470060.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.4,
    reviews: 57,
    badge: null,
    description: "Robust skrapstolpe Bedford skrapstolpe från EBI erbjuder allt en katt kan önska sig: en skrapstolpe av mjuk plysch med en hydda i nedre delen och 2 våningar. De 4 skrapstolparna är gjorda av rejäl sisal så att katten kan klia sig hur mycket som helst. Den stoppade leksaken på",
    tags: [],
    inStock: true,
  },
{
    id: 22,
    slug: "catit-catit-senses-2-0-spielschiene-wave-22",
    name: "CATIT Senses 2.0 game rail Wave",
    brand: "CATIT",
    category: "tillbehor",
    price: 230,
    originalPrice: 270,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/43155w-hag.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.6,
    reviews: 129,
    badge: null,
    description: "De nya spelskenorna har ett rakt skenelement som gör att de kan kombineras med de bredare och mer stabila baserna i Senses 2.0-produkterna. Det nya elementet möjliggör ännu mer mångsidig design och kan till och med användas tillsammans med de gamla blå spelskenorna! De",
    tags: [],
    inStock: true,
  },
{
    id: 25,
    slug: "catit-catit-senses-2-0-ball-dome-ball-kuppel-25",
    name: "Catit Senses 2.0 Ball Dome",
    brand: "CATIT",
    category: "tillbehor",
    price: 320,
    originalPrice: 405,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/43144-hag.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.6,
    reviews: 130,
    badge: null,
    description: "Senses 2.0 Ball Dome rörelseaktiverad bollleksak med svängplatta Tilltalar din katts naturliga jaktinstinkt Håller din katt sysselsatt och aktiv när du är borta Två spellägen: Sensor och kontinuerlig Tillverkad av BPA-fria material Batterier ingår ej",
    tags: [],
    inStock: true,
  },
{
    id: 26,
    slug: "trixie-trixie-junior-kratzstamm-mit-spieltrommel-26",
    name: "Trixie Junior skrapstolpe med lektrumma",
    brand: "Trixie",
    category: "mobler",
    price: 150,
    originalPrice: 220,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/42930.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.4,
    reviews: 238,
    badge: null,
    description: "Sisal: ø 4 mm/plysch (polyester): 150 g/m² Färg: lila Höjd: ca. 47 cm Basyta: ca. ø 26 cm Bål: ca. ø 6,5 cm",
    tags: [],
    inStock: true,
  },
{
    id: 33,
    slug: "ebi-ebi-kratzbaum-classictree-ceylan-grau-33",
    name: "EBI skrapstolpe Classictree Ceylan - grå",
    brand: "EBI",
    category: "mobler",
    price: 945,
    originalPrice: 1145,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/431421406.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.4,
    reviews: 74,
    badge: null,
    description: "Husformad grå skrapstolpe med flera nivåer Den klassiska Ceylan skrapstolpen erbjuder flera nivåer. Den stabila bottenplattan är utrustad med tre upprättstående skrapstolpar och en tvärstolpe. På första våningen finns ett trevligt stort katthus där din katt kan dra sig tillbaka för att koppla av",
    tags: [],
    inStock: true,
  },
{
    id: 37,
    slug: "duvo-duvoplus-cat-toy-knisternde-maus-grau-37",
    name: "Duvoplus Cat Toy sprakande mus - grå",
    brand: "DUVO",
    category: "tillbehor",
    price: 30,
    originalPrice: 50,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/5414365347772_prd_webl.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.3,
    reviews: 124,
    badge: null,
    description: "Den roliga musen från duvoplus är gjord av mjuk plysch och ger sprakande ljud som en extra kul faktor. Leksaken innehåller även lekstimulerande kattmynta. Mått: 18 x 8 x 2 cm",
    tags: [],
    inStock: true,
  },
{
    id: 41,
    slug: "kerbl-kerbl-kletterwand-montblanc-6-teilig-41",
    name: "Kerbl klättervägg Montblanc 6 delar",
    brand: "Kerbl",
    category: "tillbehor",
    price: 1090,
    originalPrice: 1265,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/ak-81634.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.3,
    reviews: 33,
    badge: null,
    description: "• för att fästa på väggen • bestående av 6 delar • 3 löpbrädor 29,5 x 22,5 cm • 1 vadderad liggbräda 40,5 x 31 cm • 1 ramp med sisalkåpa 44 x 14 cm • 1 grotta 37 x 37 x 30 cm • rymmer upp till 10 klätterväggssystem även din katt kan klättra upp till 10 kg utrymme.",
    tags: [],
    inStock: true,
  },
{
    id: 49,
    slug: "trixie-trixie-scratch-me-kratzstamm-50-cm-49",
    name: "Trixie Scratch Me skrapstolpe - 50 cm",
    brand: "Trixie",
    category: "mobler",
    price: 175,
    originalPrice: 250,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4306-trxi.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.4,
    reviews: 231,
    badge: null,
    description: "Scratch Me-skrapstolpen är helt inlindad i naturlig sisal (både bålen och bottenplattan) och erbjuder gott om plats för att slipa klor. Den roterande leksaksvagnen, som sitter högst upp på bagageutrymmet och är utrustad med en leksak på ett gummiband, och ett ägg garanterar kul",
    tags: [],
    inStock: true,
  },
{
    id: 50,
    slug: "trixie-trixie-kratzbrett-mit-plusch-56-cm-beige-50",
    name: "Trixie skrapbräda med plysch, 56 cm - beige",
    brand: "Trixie",
    category: "mobler",
    price: 75,
    originalPrice: 110,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/43071-trxi.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.4,
    reviews: 255,
    badge: null,
    description: "En skrapbräda skyddar dina möbler och väggar från din katts naturliga skrapvanor. Denna hängande skrapbräda är helt täckt med plysch på baksidan. Framtill finns plyschlister nertill och upptill med en bredd på ca. 8 cm. Den totala dimensionen är c",
    tags: [],
    inStock: true,
  },
{
    id: 51,
    slug: "trixie-trixie-sisal-platte-mit-kratzstamm-50-cm-51",
    name: "Trixie sisal tallrik med skrapstolpe - 50 cm",
    brand: "Trixie",
    category: "mobler",
    price: 130,
    originalPrice: 185,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4309-trxi.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.4,
    reviews: 248,
    badge: null,
    description: "Denna skrapstolpe är helt inlindad i naturlig sisal (både stammen och bottenplattan) och erbjuder gott om plats för att slipa klor. Leksaken på bandet, som är fäst på toppen av stammen, garanterar kul. Basarea: ca. 31 cm diameter Ståldiameter: ca. 7 cm Höjd: ca. 50 cm Övrigt",
    tags: [],
    inStock: true,
  },
{
    id: 52,
    slug: "trixie-trixie-kratzbrett-katzen-kontur-52",
    name: "Trixie skrapbräda kattkontur",
    brand: "Trixie",
    category: "mobler",
    price: 70,
    originalPrice: 100,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/43161(1).jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.4,
    reviews: 243,
    badge: null,
    description: "Sisal/trä sisal matta för upphängning med kattmynta mått: ca. 21 × 56 cm",
    tags: [],
    inStock: true,
  },
{
    id: 58,
    slug: "catit-catit-senses-massage-center-58",
    name: "CATIT Senses Massage Center",
    brand: "CATIT",
    category: "tillbehor",
    price: 230,
    originalPrice: 275,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/50720-hag.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.6,
    reviews: 131,
    badge: null,
    description: "En katts sinnen är extraordinära. De kan höra ljud som överstiger vår förmåga att höra. De kan se saker som är osynliga för oss. Och med sitt luktsinne, smak och känsel upplever de vår värld som vi bara kan föreställa oss. Catit Design massagecenter",
    tags: [],
    inStock: true,
  },
{
    id: 60,
    slug: "catit-catit-fresh-clear-trinkbrunnen-2l-blau-60",
    name: "CATIT Fresh+Clear dricksfontän 2L - blå",
    brand: "CATIT",
    category: "tillbehor",
    price: 275,
    originalPrice: 385,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/50053-hag.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.6,
    reviews: 145,
    badge: null,
    description: "Catit Design Fresh & Clear Drinking Fountain ger en inomhuskälla med rinnande vatten som uppmuntrar ditt husdjur att dricka mer. Att uppmuntra din katt att dricka mer vatten hjälper till att förhindra att kristaller bildas, vilket kan leda till urinvägsproblem",
    tags: [],
    inStock: true,
  },
{
    id: 61,
    slug: "karlie-karlie-kratzbaum-arvid-grau-61",
    name: "Karlie skrapstolpe Arvid - grå",
    brand: "Karlie",
    category: "mobler",
    price: 720,
    originalPrice: 990,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/522668.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.3,
    reviews: 95,
    badge: null,
    description: "Karlie Arvid skrapstolpe är en praktisk sov- och repmöbelkombination. Katten har utrymme att sova, leka och observera på tre nivåer. Huskatter kan vila ostört i den plyschklädda sovgrottan och plattformarna är också gjorda med plysch",
    tags: [],
    inStock: true,
  },
{
    id: 65,
    slug: "kerbl-kerbl-wollmause-2-stuck-65",
    name: "Kerbl ullmöss - 2 st",
    brand: "Kerbl",
    category: "tillbehor",
    price: 20,
    originalPrice: 35,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wollmaeuse.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.3,
    reviews: 33,
    badge: null,
    description: "Två söta ullmöss för lek och jakt med en storlek på ca. 4,5 cm. Olika färger. Tyvärr går det inte att välja färg då färgen är vald beroende på lager.",
    tags: [],
    inStock: true,
  },
{
    id: 66,
    slug: "karlie-karlie-kratzbaum-kitty-scratchy-66",
    name: "Karlie kattträd Kitty Scratchy",
    brand: "Karlie",
    category: "mobler",
    price: 360,
    originalPrice: 500,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/low_jpg-34997.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.3,
    reviews: 102,
    badge: null,
    description: "Skrapstolpskombination speciellt för kattungar. Med böjd sisal skrapyta. För artanpassad klovård. Med gosig plysch. Mått: 50 x 24 x 40 cm Färg: brun-beige",
    tags: [],
    inStock: true,
  },
{
    id: 71,
    slug: "catit-catit-senses-speed-circuit-tempo-spielschiene-71",
    name: "CATIT Senses Speed ​​​​Circuit - hastighetsspelbana",
    brand: "CATIT",
    category: "tillbehor",
    price: 250,
    originalPrice: 300,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/50735-hag.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.6,
    reviews: 130,
    badge: null,
    description: "En katts sinnen är extraordinära. De kan höra ljud som överstiger vår förmåga att höra. De kan se saker som är osynliga för oss. Och med sitt luktsinne, smak och känsel upplever de vår värld som vi bara kan föreställa oss. Syn, hörsel och känsel är",
    tags: [],
    inStock: true,
  },
{
    id: 75,
    slug: "ebi-ebi-kratzbaum-comfort-stockholm-grau-75",
    name: "EBI Comfort Stockholm kattträd - grå",
    brand: "EBI",
    category: "mobler",
    price: 2455,
    originalPrice: 2925,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/431444627.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.4,
    reviews: 72,
    badge: null,
    description: "Högkvalitativ skrapstolpe i skandinavisk stil Stockholmskrapstolpen är en högkvalitativ, funktionell skrapmöbel i skandinavisk stil. De ofärdiga granträelementen i kombination med det lyxigt bearbetade tyget ger optimal komfort. De fyra kuddarna och sovhytten",
    tags: [],
    inStock: true,
  },
{
    id: 76,
    slug: "beeztees-beeztees-katzenangel-fruhlingsblumen-76",
    name: "Beeztees Cat Angel Vårblommor",
    brand: "Beeztees",
    category: "tillbehor",
    price: 60,
    originalPrice: 80,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/440718.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.3,
    reviews: 47,
    badge: null,
    description: "Ta in våren i ditt hem med den vackra vårblomman Katzenangel från Beeztees. Kattleksaken är idealisk för att leka tillsammans och stärker bandet mellan dig och din katt. Kattens fiskespö finns med en vacker ros, en tusensköna eller en",
    tags: [],
    inStock: true,
  },
{
    id: 78,
    slug: "kerbl-drinkwell-mini-trinkbrunnen-1-2-l-78",
    name: "Drinkwell Mini Drinking Fountain 1,2 L",
    brand: "Kerbl",
    category: "tillbehor",
    price: 555,
    originalPrice: 635,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/ak-82281_qua.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.3,
    reviews: 36,
    badge: null,
    description: "Praktisk försörjning av alltid färskt och filtrerat vatten! Den nya Drinkwell Platinum vattentråg uppmuntrar ditt husdjur att dricka mer av det färska, syrerika vattnet. Vattentråget är utvecklat av veterinärer och skyddar ditt husdjurs hälsa och minskar",
    tags: [],
    inStock: true,
  },
{
    id: 79,
    slug: "procyon-procyon-rollbarer-silikon-doppelnapf-79",
    name: "PROCYON rullbar dubbelskål i silikon",
    brand: "PROCYON",
    category: "tillbehor",
    price: 90,
    originalPrice: 155,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/ps-90366-2.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.5,
    reviews: 53,
    badge: null,
    description: "Den rullbara dubbelskålen i silikon är en absolut idealisk resepartner för alla längre resor med hund. När den är ihoprullad kan den stuvas undan i valfri väska för att spara utrymme och när en paus uppstår kan en komplett matplats med två skålar sättas upp på några sekunder. Alla som duttat honom en gång",
    tags: [],
    inStock: true,
  },
{
    id: 82,
    slug: "ebi-ebi-kratzbaum-trend-curacao-82",
    name: "EBI Cat Tree Trend Curacao",
    brand: "EBI",
    category: "mobler",
    price: 1840,
    originalPrice: 2165,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/431-405574-EBI_1.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.4,
    reviews: 52,
    badge: null,
    description: "Mellanstor skrapstolpe med en stor, vadderad grotta som står på två sisalstolpar (med öppning / gjord av vattenhyacintblad), med tre liggplatser och en vadderad solsoffa inramad med vattenhyacintblad. Det finns plyschbollar på resårband på två av liggplatserna",
    tags: [],
    inStock: true,
  },
{
    id: 83,
    slug: "ebi-ebi-kratzbaum-trend-grenada-83",
    name: "EBI Cat Tree Trend Grenada",
    brand: "EBI",
    category: "mobler",
    price: 1355,
    originalPrice: 1730,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4047059405581_prd_webl1.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.4,
    reviews: 70,
    badge: null,
    description: "Skrapstolpe med en stor vadderad grotta stående på två sisalstolpar (med öppning / gjorda av vattenhyacintblad) med liggyta och vadderad solsoffa kantad av vattenhyacintblad. Det hänger en plyschboll på det elastiska bandet som är fäst vid solstolen, w",
    tags: [],
    inStock: true,
  },
{
    id: 90,
    slug: "procyon-procyon-schnuffelwiese-grun-90",
    name: "PROCYON Sniffing Meadow - Grön",
    brand: "PROCYON",
    category: "tillbehor",
    price: 275,
    originalPrice: 330,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/schnueffelwiese.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.5,
    reviews: 59,
    badge: null,
    description: "Med det nya godissökningsspelet Schnüffelwiese kan din hund vara aktiv, få sin belöning direkt och ha mycket roligt! På den ca. 50 x 50 cm matta, godsaker eller till och med hela torrfodermåltider placeras mellan tyget \"grässtrån\".",
    tags: [],
    inStock: true,
  },
{
    id: 91,
    slug: "d-d-home-d-d-kratztonne-cat-dome-pura-vida-schwarz-91",
    name: "D&D skrapfat Cat-Dome PURA VIDA - svart",
    brand: "D&D Home",
    category: "mobler",
    price: 780,
    originalPrice: 1145,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/431-431832-ebi.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.5,
    reviews: 42,
    badge: null,
    description: "Denna skrappipa är helt limmad med robust jutetyg. Den har två grottangångar, två plyschvåningar och en vadderad säng på toppen av fatet. Med gosig plyschkant vid öppningar och kanter. Högkvalitativt utförande och skadliga ämnen",
    tags: [],
    inStock: true,
  },
{
    id: 92,
    slug: "catit-catit-catlove-kratzbrett-giraffe-92",
    name: "CATIT CatLove giraffskrapbräda",
    brand: "CATIT",
    category: "mobler",
    price: 95,
    originalPrice: 125,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/34905-hag.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.6,
    reviews: 156,
    badge: null,
    description: "Katter behöver instinktivt klia sig. Att repa hjälper till att vässa klorna och gnider bort det döda yttre lagret av klorna. De sträcker och rör på sina kroppar och bränner därmed av energi. Catit-skrapbrädorna med kattmynta ger din katt en räfflad repa",
    tags: [],
    inStock: true,
  },
{
    id: 94,
    slug: "catit-catit-play-pirates-tur-kratzbrett-94",
    name: "CATIT Play Pirates dörrskrapbräda",
    brand: "CATIT",
    category: "mobler",
    price: 140,
    originalPrice: 170,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/42487-hag.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.6,
    reviews: 148,
    badge: null,
    description: "Åk på en stor privatresa med oss ​​och upplev fantastiska äventyr med nya Catit Play Pirates! Se din katt jaga en påse med guld eller tända en granat som en riktig pirat! Var och en av dessa leksaker är fyllda med frestande kattmynta. Längd: ca. 48 cm",
    tags: [],
    inStock: true,
  },
{
    id: 95,
    slug: "procyon-procyon-multifunktions-futterschaufel-95",
    name: "PROCYON multifunktionell foderskopa",
    brand: "PROCYON",
    category: "tillbehor",
    price: 55,
    originalPrice: 145,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/ps-40243.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.5,
    reviews: 50,
    badge: null,
    description: "Den multifunktionella matskålen är den perfekta följeslagaren på språng och på resa. Det är en hopfällbar matskeda där matbehållaren är gjord av hygieniskt silikon. Det ergonomiskt formade handtaget kan tas bort från matbehållaren och kan användas som en praktisk",
    tags: [],
    inStock: true,
  },
{
    id: 97,
    slug: "kerbl-kerbl-kletterwand-alps-4-teilig-97",
    name: "Kerbl klättervägg Alperna 4-delad",
    brand: "Kerbl",
    category: "mobler",
    price: 765,
    originalPrice: 905,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/alps.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.3,
    reviews: 55,
    badge: null,
    description: "4-delat steg med sisal: 15 cm, Ø 9 cm Liggbräda med avtagbar dyna: 40 x 31 cm Sisalpelare som ramp: 50 cm, Ø 9 cm Hängmatta: 35 x 33 cm Material: Massivt trä för väggmontering Sisal limmad på pelaren",
    tags: [],
    inStock: true,
  },
{
    id: 98,
    slug: "procyon-procyon-katzenspielmaus-10-cm-98",
    name: "PROCYON kattleksaksmus - 10 cm",
    brand: "PROCYON",
    category: "tillbehor",
    price: 10,
    originalPrice: 30,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/maus.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.5,
    reviews: 30,
    badge: null,
    description: "Med sin ståtliga storlek på ca. 10 cm utan svans eller ca. 24 cm inklusive svans, den söta kattleksaksmusen tillför mycket nöje i kattens liv.",
    tags: [],
    inStock: true,
  },
{
    id: 103,
    slug: "procyon-procyon-ladi-mat-schleckplatte-wobbler-103",
    name: "PROCYON Ladi Mat slickplatta wobbler",
    brand: "PROCYON",
    category: "tillbehor",
    price: 95,
    originalPrice: 155,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/wobbler.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.5,
    reviews: 40,
    badge: null,
    description: "Slickplattor är perfekta för att hålla hundar sysselsatta. Bred bara ut en godbit på Ladi Mat så får din hund en lång, välsmakande goding. För att kyla ner kan slickplattan även frysas in tillsammans med godsakerna. Ladi Mat wobblern är längst ner",
    tags: [],
    inStock: true,
  },
{
    id: 104,
    slug: "duvo-duvoplus-kratzbaum-new-york-dunkelgrau-104",
    name: "Duvoplus skrapstolpe New York - mörkgrå",
    brand: "DUVO",
    category: "mobler",
    price: 1045,
    originalPrice: 1200,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/802811.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.3,
    reviews: 111,
    badge: null,
    description: "Lyxig skrapstolpe för hemmet New York-skrapstolpen från duvoplus är ett lyxigt lekparadis för din katt eller katter. Skrapstolpen har trappsteg, två små nischer där din katt kan vila i fred, och på toppen finns flera plattformar som låter din katt se sitt U",
    tags: [],
    inStock: true,
  },
{
    id: 110,
    slug: "duvo-duvoplus-kratzstamm-billy-110",
    name: "Duvoplus Billy skrapstolpe",
    brand: "DUVO",
    category: "mobler",
    price: 110,
    originalPrice: 185,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/5414365365714_prd_webl.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.3,
    reviews: 121,
    badge: null,
    description: "Billy skrapstolpe från duvoplus är en kompakt skrapstolpe som är gjord av sisal och plysch. Spelbollen ger ytterligare motivation genom att uppmuntra användningen av skrapstolpen. Denna skrapstolpe är lämplig för unga kattungar. Hela stången täckt av sisal. Mjuk och bekväm",
    tags: [],
    inStock: true,
  },
{
    id: 111,
    slug: "ebi-ebi-cat-toy-ball-chaser-wei-grun-111",
    name: "EBI Cat Toy Ball Chaser - vit/grön",
    brand: "EBI",
    category: "tillbehor",
    price: 140,
    originalPrice: 220,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4047059472064_prd_webl.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.4,
    reviews: 76,
    badge: null,
    description: "Ball Chaser från EBI är en rolig elektronisk leksak för katter som rullar runt ditt hus på egen hand. Ball Chaser har 3 olika positioner: Position 1 = färd med röda blinkande ljus, Position 2 = laserstråle pekar i alla riktningar, Position 3 = färd med blinkande ljus",
    tags: [],
    inStock: true,
  },
{
    id: 112,
    slug: "duvo-duvoplus-cat-toy-knisternde-maus-braun-112",
    name: "Duvoplus Cat Toy sprakande mus - brun",
    brand: "DUVO",
    category: "tillbehor",
    price: 30,
    originalPrice: 50,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/5414365349547_prd_webl.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.3,
    reviews: 100,
    badge: null,
    description: "Den roliga musen från duvoplus är gjord av mjuk plysch och ger sprakande ljud som en extra kul faktor. Leksaken innehåller även lekstimulerande kattmynta. Mått: 18 x 8 x 2 cm",
    tags: [],
    inStock: true,
  },
{
    id: 113,
    slug: "duvo-duvoplus-cat-toy-shaking-berry-maus-113",
    name: "Duvoplus Cat Toy Shaking Berry Mouse",
    brand: "DUVO",
    category: "tillbehor",
    price: 45,
    originalPrice: 70,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/5414365349578_prd_webl.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.3,
    reviews: 120,
    badge: null,
    description: "Shaking Berry från duvoplus är en vibrerande plyschmus. När du drar i svansen börjar den röra sig slumpmässigt, vilket kommer att fascinera och animera din katt i timmar. Mått: 8 x 7 x 5 cm",
    tags: [],
    inStock: true,
  },
{
    id: 114,
    slug: "duvo-duvoplus-cat-toy-knitted-mause-braun-2-stuck-114",
    name: "Duvoplus Cat Toy Stickade Möss brun - 2 st",
    brand: "DUVO",
    category: "tillbehor",
    price: 20,
    originalPrice: 25,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/5414365347925_pck_webl.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.3,
    reviews: 106,
    badge: null,
    description: "Leksak av stickat tyg Med en rolig svans av mocka Med naturlig kattmynta på insidan Tillfredsställer din katts jaktinstinkter Uppmuntrar till rörelse Mått: 13,5 x 4,5 x 2,5 cm 2 st.",
    tags: [],
    inStock: true,
  },
{
    id: 115,
    slug: "duvo-duvoplus-cat-toy-knitted-ball-mit-federn-braun-115",
    name: "Duvoplus kattleksak stickad boll med fjädrar - brun",
    brand: "DUVO",
    category: "tillbehor",
    price: 10,
    originalPrice: 20,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/5414365347987_prd_webl.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.3,
    reviews: 118,
    badge: null,
    description: "Stickad tygleksak med fjädrar Bollen låter när du flyttar den. Tillfredsställer din katts jaktinstinkt. Uppmuntrar till rörelse. Mått: 16 x 4 x 4 cm",
    tags: [],
    inStock: true,
  },
{
    id: 116,
    slug: "d-d-home-d-d-rocco-tretkissen-waschbar-116",
    name: "D&D Rocco Kick Cushion - Raccoon",
    brand: "D&D Home",
    category: "tillbehor",
    price: 85,
    originalPrice: 120,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4047059462041_prd_webl.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.5,
    reviews: 35,
    badge: null,
    description: "40 cm lång gosedjur gjord av mjuk chenille Mjuk fluffig svans med klocka Återfyllbar med en påse fylld med kattmynta med kardborrstängning Inkluderar påsar med kattmynta Vacker design i form av en tvättbjörn Mått: 40 x 11cm",
    tags: [],
    inStock: true,
  },
{
    id: 117,
    slug: "d-d-home-d-d-katzennapf-jasper-sand-200ml-117",
    name: "D&D kattskål Jasper - sand 200ml",
    brand: "D&D Home",
    category: "tillbehor",
    price: 95,
    originalPrice: 145,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4047059462874_prd_webl.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.5,
    reviews: 59,
    badge: null,
    description: "Jasper matskål är en keramikskål som passar både mat och vatten. Med en väggtjocklek på cirka 8 mm är Jasper slagtålig. Skalets botten har gummidubbar för att förhindra repor på golvet. hindrar morrhåren från att nå kanterna",
    tags: [],
    inStock: true,
  },
{
    id: 118,
    slug: "d-d-home-d-d-rocco-tretkissen-fuchs-118",
    name: "D&D Rocco Kick Cushion - Räv",
    brand: "D&D Home",
    category: "tillbehor",
    price: 85,
    originalPrice: 120,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4047059462034_prd_webl.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.5,
    reviews: 34,
    badge: null,
    description: "40 cm lång kramleksak av mjuk chenille Mjuk fluffig svans med klocka Påfyllningsbar med en påse fylld med kattmynta med kardborrestängning Inkluderar påsar med kattmynta Vacker design i form av en räv Mått: 40 x 11cm",
    tags: [],
    inStock: true,
  },
{
    id: 119,
    slug: "d-d-home-d-d-rocco-tretkissen-stinktier-119",
    name: "D&D Rocco Kick Cushion - Skunk",
    brand: "D&D Home",
    category: "tillbehor",
    price: 85,
    originalPrice: 120,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4047059462027_prd_webl.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.5,
    reviews: 53,
    badge: null,
    description: "40 cm lång gosedjur gjord av manchester eller räfflad sammet Mjuk fluffig svans med klocka Påfyllningsbar med en påse fylld med kattmynta med kardborrefäste Inkluderar påsar med kattmynta Vacker design i form av en skunk Mått: 40 x 11 cm",
    tags: [],
    inStock: true,
  },
{
    id: 120,
    slug: "d-d-home-d-d-nachfullbares-tretkissen-zoey-120",
    name: "D&D påfyllningsbar sparkkudde Zoey",
    brand: "D&D Home",
    category: "tillbehor",
    price: 75,
    originalPrice: 115,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4047059482070_prd_webl.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.5,
    reviews: 30,
    badge: null,
    description: "Runt, fyllt huvud för att sparka, platt knaprig kropp för att gosa. Påfyllningsbar kattmyntapåse med kardborreknäppning. Innehåller en påse med Happy Cats örtblandning. Uppmuntrar din katt att leka. Happy Cat design med teddypäls och bomullstyg. Mått: 15 x 5 x 12 cm",
    tags: [],
    inStock: true,
  },
{
    id: 121,
    slug: "ebi-ebi-pet-feeder-2in1-blau-121",
    name: "EBI Pet Feeder 2in1 - Blå",
    brand: "EBI",
    category: "tillbehor",
    price: 325,
    originalPrice: 435,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4047059442975_prd_webl.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.4,
    reviews: 74,
    badge: null,
    description: "Den kompakta Pet Feeder mat- och drickskålen är lämplig för katter och små hundar. Den konstanta vattencirkulationen håller vattnet fräscht. De avtagbara komponenterna gör behållaren lätt att rengöra. Kolfibrerna filtrerar vattnet och neutraliserar lukt och smak.",
    tags: [],
    inStock: true,
  },
{
    id: 122,
    slug: "duvo-duvoplus-kratzstamm-becky-122",
    name: "Duvoplus skrapstolpe Becky",
    brand: "DUVO",
    category: "mobler",
    price: 115,
    originalPrice: 200,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/5414365365707_prd_webl.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.3,
    reviews: 112,
    badge: null,
    description: "Becky skrapstolpe från duvoplus är en kompakt skrapstolpe som är gjord av sisal och plysch. Spelbollen ger ytterligare motivation genom att uppmuntra användningen av skrapstolpen. Denna skrapstolpe är lämplig för unga kattungar. Hela stången täckt av sisal. Mjuk och bekväm",
    tags: [],
    inStock: true,
  },
{
    id: 123,
    slug: "duvo-duvoplus-kratzstamm-paw-beige-123",
    name: "Duvoplus skrapstolpe Paw Beige",
    brand: "DUVO",
    category: "mobler",
    price: 175,
    originalPrice: 250,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/5414365450106_prd_webl.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.3,
    reviews: 115,
    badge: null,
    description: "Duvoplus Paw skrapstolpe är en kompakt skrapstolpe i form av en söt katttass, gjord med sisal och plysch. Spelbollen ger extra kul och motivation att skrapa på stolpen. Sisal skrapstolpe höjd: 60 cm Diameter på skrapstolpe: 60 mm Med lekboll söt katttass M",
    tags: [],
    inStock: true,
  },
{
    id: 124,
    slug: "ebi-ebi-cat-toy-double-spinner-wei-grun-124",
    name: "EBI Cat Toy Double Spinner - vit/grön",
    brand: "EBI",
    category: "tillbehor",
    price: 195,
    originalPrice: 285,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4047059472088_prd_webl.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.4,
    reviews: 62,
    badge: null,
    description: "Double Spinner från EBI är en superkul elektronisk kattleksak som kan rulla runt i ditt hus på egen hand. Spinnern kan rotera 360° runt sin axel och röra sig framåt och bakåt, vilket gör att den kan ta sig ur de flesta fastnade situationer. Konstigaren",
    tags: [],
    inStock: true,
  },
{
    id: 125,
    slug: "ebi-ebi-cat-toy-teleskop-teaser-katzenangel-125",
    name: "EBI Cat Toy teleskopisk teaser kattfiskespö",
    brand: "EBI",
    category: "tillbehor",
    price: 150,
    originalPrice: 220,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4047059480854_prd_webl.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.4,
    reviews: 62,
    badge: null,
    description: "Teleskopstången från EBI kan förlängas från 40 till 75 cm. Den fjäderbelastade linan rör sig upp och ner när den automatiskt roterar runt stången. På grund av den snabba rörelsen är den väldigt intressant för katten. Ytterligare en ingår i leveransen",
    tags: [],
    inStock: true,
  },
{
    id: 126,
    slug: "ebi-ebi-cat-toy-rc-cat-chaser-wei-grun-126",
    name: "EBI Cat Toy RC Cat Chaser - vit/grön",
    brand: "EBI",
    category: "tillbehor",
    price: 350,
    originalPrice: 580,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4047059472071_prd_webl.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.4,
    reviews: 78,
    badge: null,
    description: "RC Cat Chaser från EBI är en superkul elektronisk kattleksak med fjärrkontroll. Vänster, höger, framåt eller bakåt, denna leksak erbjuder massor av skoj för unga och gamla, men naturligtvis också för din katt! Silikonrullarna kan lätt övervinna hinder som mattor",
    tags: [],
    inStock: true,
  },
{
    id: 127,
    slug: "d-d-home-d-d-gebogenes-wandregal-aus-pappe-david-braun",
    name: "D&D böjd vägghylla i kartong David - brun/beige",
    brand: "D&D Home",
    category: "mobler",
    price: 260,
    originalPrice: 385,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4047059484494_prd_webl.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.5,
    reviews: 40,
    badge: null,
    description: "Katter är trädklättrare som älskar att klättra högt. Du behöver en utsiktsplats och känner dig säkrare högt upp än på marken. DAVID vägghyllor från D&D Home | I LOVE Happy Cats, utvecklad i samarbete med kattbeteendeisten Anneleen Bru, är ute",
    tags: [],
    inStock: true,
  },
{
    id: 128,
    slug: "d-d-home-d-d-kratzplayground-faye-dreiteilig-braun-beig",
    name: "D&D skrapa lekplats Faye tredelad - brun/beige",
    brand: "D&D Home",
    category: "mobler",
    price: 600,
    originalPrice: 765,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4047059484463_prd_webl.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.5,
    reviews: 43,
    badge: null,
    description: "FAYE från D&D Home | I LOVE Happy Cats är en tvåvånings \"lekplats\" och koj gjord av robust wellpapp som säkerligen kommer att bli en hit hos din katt eftersom katter ÄLSKAR kartong! MDF-sidorna ger den ett lyxigt utseende och extra styrka. De tre delarna kan",
    tags: [],
    inStock: true,
  },
{
    id: 129,
    slug: "d-d-home-d-d-nachfullteil-fur-gebogenes-wandregal-david",
    name: "D&D refill för böjd vägghylla David",
    brand: "D&D Home",
    category: "mobler",
    price: 165,
    originalPrice: 240,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4047059484593_prd_webl.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.5,
    reviews: 54,
    badge: null,
    description: "Katter är trädklättrare som älskar att klättra högt. Du behöver en utsiktsplats och känner dig säkrare högt upp än på marken. DAVID vägghyllor från D&D Home | I LOVE Happy Cats, utvecklad i samarbete med kattbeteendeisten Anneleen Bru, är ute",
    tags: [],
    inStock: true,
  },
{
    id: 130,
    slug: "duvo-duvoplus-kratzbaum-noah-130",
    name: "Duvoplus Noah skrapstolpe",
    brand: "DUVO",
    category: "mobler",
    price: 595,
    originalPrice: 820,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/5414365440213_prd_webl.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.3,
    reviews: 108,
    badge: null,
    description: "Noah från duvoplus är en liten, stabil skrapstolpe med 1 bekväm liggplattform av mjuk plysch, så att det finns tillräckligt med utrymme för din katt att klia, titta och vila. Skrapstolpen är gjord av lövträ och har ett vackert naturligt utseende. Diametern på stolpen",
    tags: [],
    inStock: true,
  },
{
    id: 132,
    slug: "d-d-home-d-d-wandhangematte-otis-grau-132",
    name: "D&D vägghängmatta Otis - grå",
    brand: "D&D Home",
    category: "mobler",
    price: 240,
    originalPrice: 360,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/4047059481271_prd_webl.jpg",
    placeholder: "🛋️",
    weight: null,
    rating: 4.5,
    reviews: 40,
    badge: null,
    description: "Katter ÄLSKAR hängmattor eftersom de ger en mycket lugnande, hängande yta som katter älskar att sova och vila i. OTIS från D&D Hem | I LOVE Happy Cats är en vacker, modern och minimalistisk vägghängmatta som omfamnar detta faktum och ger en bekväm",
    tags: [],
    inStock: true,
  },
{
    id: 137,
    slug: "beeztees-beeztees-matatabi-spray-50-ml-137",
    name: "Beeztees Matatabi Spray - 50 ml",
    brand: "Beeztees",
    category: "tillbehor",
    price: 25,
    originalPrice: 40,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/425490.jpg",
    placeholder: "✨",
    weight: "0,05 1L",
    rating: 4.3,
    reviews: 39,
    badge: null,
    description: "Med denna Matatabi-spray från Beeztees kan du ge ännu mer underhållning för din katt. Matatabi har en stimulerande effekt på många katter och ökar nöjet att leka med sina leksaker. Dessutom kan det hjälpa till att lugna stressade katter. Genom att applicera sprayen på dina favoritleksaker",
    tags: [],
    inStock: true,
  },
{
    id: 138,
    slug: "beeztees-beeztees-kitten-lama-mit-gerstenschalen-138",
    name: "Beeztees kattunge lama med kornskal",
    brand: "Beeztees",
    category: "tillbehor",
    price: 45,
    originalPrice: 60,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/430550.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.3,
    reviews: 48,
    badge: null,
    description: "När en kattunge är ung är det roligt att testa olika spel och material för att experimentera med vad kattungen gillar bäst. Beeztees Kitten Toy Lama är perfekt för detta! Laman är fylld med kornskal så att ungdjuret kan känna sig bekvämt när det leker",
    tags: [],
    inStock: true,
  },
{
    id: 139,
    slug: "beeztees-beeztees-katzenspielzeug-lama-ilko-rosa-139",
    name: "Beeztees kattleksak Lama Ilko - rosa",
    brand: "Beeztees",
    category: "tillbehor",
    price: 55,
    originalPrice: 75,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/440665.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.3,
    reviews: 40,
    badge: null,
    description: "En katt som leker med en lama är en sällsynt syn. Beeztees kattleksak Ilko är en rolig lama med en något ovanlig färg: Ilkos päls är rosa. Laman är gjord av polyester och innehåller kattmynta för extra kul. - tillverkad av polyester - ingår",
    tags: [],
    inStock: true,
  },
{
    id: 146,
    slug: "lebon-lebon-thermomatte-bask-schwarz-80-x-50-cm-146",
    name: "Lebon termomatta Bask - svart - 80 x 50 cm",
    brand: "Lebon",
    category: "tillbehor",
    price: 170,
    originalPrice: 220,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/ol-196000-var.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.4,
    reviews: 50,
    badge: null,
    description: "Den robusta och högkvalitativa termomattan BASK från Lebon kan användas flexibelt. Oavsett om det är hemma, i bilen eller på resande fot skyddar mattan golv och klädsel från hundhår och smuts. Det högkvalitativa skummet är mycket stabilt och formstabilt, skyddar fogarna från hårda golv och säkerställer",
    tags: [],
    inStock: true,
  },
{
    id: 147,
    slug: "lebon-lebon-thermomatte-bask-schwarz-100-x-70-cm-147",
    name: "Lebon termomatta Bask - svart - 100 x 70 cm",
    brand: "Lebon",
    category: "tillbehor",
    price: 255,
    originalPrice: 330,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/ol-196000-var.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.4,
    reviews: 36,
    badge: null,
    description: "Den robusta och högkvalitativa termomattan BASK från Lebon kan användas flexibelt. Oavsett om det är hemma, i bilen eller på resande fot skyddar mattan golv och klädsel från hundhår och smuts. Det högkvalitativa skummet är mycket stabilt och formstabilt, skyddar fogarna från hårda golv och säkerställer",
    tags: [],
    inStock: true,
  },
{
    id: 148,
    slug: "lebon-lebon-thermomatte-bask-schwarz-120-x-80-cm-148",
    name: "Lebon termomatta Bask - svart - 120 x 80 cm",
    brand: "Lebon",
    category: "tillbehor",
    price: 340,
    originalPrice: 435,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/ol-196000-var.jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.4,
    reviews: 53,
    badge: null,
    description: "Den robusta och högkvalitativa termomattan BASK från Lebon kan användas flexibelt. Oavsett om det är hemma, i bilen eller på resande fot skyddar mattan golv och klädsel från hundhår och smuts. Det högkvalitativa skummet är mycket stabilt och formstabilt, skyddar fogarna från hårda golv och säkerställer",
    tags: [],
    inStock: true,
  },
{
    id: 149,
    slug: "kerbl-kerbl-kuschelbett-kids-rosa-149",
    name: "Kerbl gossäng barn - rosa",
    brand: "Kerbl",
    category: "tillbehor",
    price: 140,
    originalPrice: 200,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/ak-82571(1).jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.3,
    reviews: 35,
    badge: null,
    description: "Kids gossängen är trots sitt namn även lämplig för vuxna katter och små hundar. Sängen har tryckknappar runt utsidan som snabbt kan förvandla den från en säng med bård till en större filt utan bård, beroende på vad som behövs. Den gosiga mjuka vara",
    tags: [],
    inStock: true,
  },
{
    id: 150,
    slug: "lebon-lebon-thermomatte-bask-grau-100-x-70-cm-150",
    name: "Lebon termomatta Bask - grå - 100 x 70 cm",
    brand: "Lebon",
    category: "tillbehor",
    price: 255,
    originalPrice: 330,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/picture-0079(2).jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.4,
    reviews: 38,
    badge: null,
    description: "Den robusta och högkvalitativa termomattan BASK från Lebon kan användas flexibelt. Oavsett om det är hemma, i bilen eller på resande fot skyddar mattan golv och klädsel från hundhår och smuts. Det högkvalitativa skummet är mycket stabilt och formstabilt, skyddar fogarna från hårda golv och säkerställer",
    tags: [],
    inStock: true,
  },
{
    id: 151,
    slug: "lebon-lebon-thermomatte-bask-grau-120-x-80-cm-151",
    name: "Lebon termomatta Bask - grå - 120 x 80 cm",
    brand: "Lebon",
    category: "tillbehor",
    price: 340,
    originalPrice: 435,
    image: "https://www.zoodrop.de/out/pictures/generated/product/1/665_665_100/picture-0079(3).jpg",
    placeholder: "✨",
    weight: null,
    rating: 4.4,
    reviews: 57,
    badge: null,
    description: "Den robusta och högkvalitativa termomattan BASK från Lebon kan användas flexibelt. Oavsett om det är hemma, i bilen eller på resande fot skyddar mattan golv och klädsel från hundhår och smuts. Det högkvalitativa skummet är mycket stabilt och formstabilt, skyddar fogarna från hårda golv och säkerställer",
    tags: [],
    inStock: true,
  }
];

export function getProduct(slug) {
  return products.find(p => p.slug === slug) ?? null;
}

export function getByCategory(cat) {
  return products.filter(p => p.category === cat);
}
