export const categories = [
  { slug: "torrfoder", name: "Torrfoder", icon: "🌾" },
  { slug: "vatfoder", name: "Våtfoder", icon: "🍖" },
  { slug: "snacks", name: "Kattsnacks", icon: "🎁" },
  { slug: "leksaker", name: "Kattleksaker", icon: "🐾" },
  { slug: "mobler", name: "Kattträd & Möbler", icon: "🌳" },
  { slug: "baddar", name: "Bäddar & Korgar", icon: "😴" },
  { slug: "skalar", name: "Skålar & Fontäner", icon: "🥣" },
  { slug: "sand", name: "Toalett & Sand", icon: "🪨" },
];

export const products = [
  // ── TORRFODER ─────────────────────────────────────────────
  {
    id: 1,
    slug: "carnilove-lax-havsorring-400g",
    name: "Carnilove Lax & Havsörring 400g",
    brand: "Carnilove",
    category: "torrfoder",
    price: 129,
    originalPrice: null,
    image: "https://images.ctfassets.net/wxpwprc19ca5/2AfhJw3FBob5vSWLwFZly6/eaae1affdc6cbee667ced0a85e61efe9/100173711.png",
    images: ["https://images.ctfassets.net/wxpwprc19ca5/2AfhJw3FBob5vSWLwFZly6/eaae1affdc6cbee667ced0a85e61efe9/100173711.png"],
    placeholder: "🌾",
    weight: "400 g",
    rating: 4.8,
    reviews: 214,
    badge: "Bästsäljare",
    description: "Spannmålsfritt torrfoder med lax och havsörring som enda proteinkällor. Carnilove är ett premiumtjeckiskt märke med naturliga, noggrant utvalda ingredienser. Utan spannmål, potatis och socker — precis vad din katt behöver.",
    tags: ["spannmålsfritt", "lax", "premiummärke"],
    inStock: true,
    sku: "CL-SS-400",
  },
  {
    id: 2,
    slug: "carnilove-lax-havsorring-1-8kg",
    name: "Carnilove Lax & Havsörring 1,8 kg",
    brand: "Carnilove",
    category: "torrfoder",
    price: 449,
    originalPrice: null,
    image: "https://images.ctfassets.net/wxpwprc19ca5/2AfhJw3FBob5vSWLwFZly6/eaae1affdc6cbee667ced0a85e61efe9/100173711.png",
    images: ["https://images.ctfassets.net/wxpwprc19ca5/2AfhJw3FBob5vSWLwFZly6/eaae1affdc6cbee667ced0a85e61efe9/100173711.png"],
    placeholder: "🌾",
    weight: "1,8 kg",
    rating: 4.8,
    reviews: 98,
    badge: null,
    description: "Spannmålsfritt torrfoder med lax och havsörring som enda proteinkällor. Carnilove är ett premiumtjeckiskt märke med naturliga, noggrant utvalda ingredienser. Utan spannmål, potatis och socker — precis vad din katt behöver.",
    tags: ["spannmålsfritt", "lax", "premiummärke"],
    inStock: true,
    sku: "CL-SS-1800",
  },
  {
    id: 3,
    slug: "carnilove-kyckling-lamm-400g",
    name: "Carnilove Kyckling & Lamm 400g",
    brand: "Carnilove",
    category: "torrfoder",
    price: 129,
    originalPrice: null,
    image: "https://images.ctfassets.net/wxpwprc19ca5/1RxYfQem46NbXm3E9q7NPI/59496a5c80e963c0c7b0a7144a6e19da/100173705.png",
    images: ["https://images.ctfassets.net/wxpwprc19ca5/1RxYfQem46NbXm3E9q7NPI/59496a5c80e963c0c7b0a7144a6e19da/100173705.png"],
    placeholder: "🌾",
    weight: "400 g",
    rating: 4.7,
    reviews: 167,
    badge: "Populär",
    description: "Torrfoder av kyckling och lamm utan spannmål. Högt proteininnehåll och rik på fettsyror. Carnilove produceras av VAFO Praha, ett av Europas mest ansedda petfood-företag.",
    tags: ["spannmålsfritt", "kyckling", "lamm"],
    inStock: true,
    sku: "CL-CL-400",
  },
  {
    id: 4,
    slug: "carnilove-kyckling-lamm-1-8kg",
    name: "Carnilove Kyckling & Lamm 1,8 kg",
    brand: "Carnilove",
    category: "torrfoder",
    price: 449,
    originalPrice: null,
    image: "https://images.ctfassets.net/wxpwprc19ca5/1RxYfQem46NbXm3E9q7NPI/59496a5c80e963c0c7b0a7144a6e19da/100173705.png",
    images: ["https://images.ctfassets.net/wxpwprc19ca5/1RxYfQem46NbXm3E9q7NPI/59496a5c80e963c0c7b0a7144a6e19da/100173705.png"],
    placeholder: "🌾",
    weight: "1,8 kg",
    rating: 4.7,
    reviews: 72,
    badge: null,
    description: "Torrfoder av kyckling och lamm utan spannmål. Högt proteininnehåll och rik på fettsyror. Carnilove produceras av VAFO Praha, ett av Europas mest ansedda petfood-företag.",
    tags: ["spannmålsfritt", "kyckling", "lamm"],
    inStock: true,
    sku: "CL-CL-1800",
  },
  {
    id: 5,
    slug: "carnilove-kalkon-lax-limited-400g",
    name: "Carnilove Kalkon & Lax Limited Ingredient 400g",
    brand: "Carnilove",
    category: "torrfoder",
    price: 149,
    originalPrice: null,
    image: "https://images.ctfassets.net/wxpwprc19ca5/55WSQ9GGHAtFs52fpN5qDS/bc9397992d8f492cb780987b59f006b3/100173708.png",
    images: ["https://images.ctfassets.net/wxpwprc19ca5/55WSQ9GGHAtFs52fpN5qDS/bc9397992d8f492cb780987b59f006b3/100173708.png"],
    placeholder: "🌾",
    weight: "400 g",
    rating: 4.9,
    reviews: 89,
    badge: "Känsliga magar",
    description: "Specialformulerat torrfoder med minimal ingredienslista — bara kalkon och lax. Perfekt för katter med känslig mage eller matallergi. Inga onödiga tillsatser.",
    tags: ["spannmålsfritt", "känslig mage", "limited ingredient"],
    inStock: true,
    sku: "CL-TS-400",
  },
  {
    id: 6,
    slug: "carnilove-vildsvinsdjur-renkott-400g",
    name: "Carnilove Vildsvin & Renkött 400g",
    brand: "Carnilove",
    category: "torrfoder",
    price: 149,
    originalPrice: 169,
    image: "https://images.ctfassets.net/wxpwprc19ca5/0quham2grJbXJciCZEgHQ/cdff56a77f4c316e6bc38fcbb7cdaf07/100173723.png",
    images: ["https://images.ctfassets.net/wxpwprc19ca5/0quham2grJbXJciCZEgHQ/cdff56a77f4c316e6bc38fcbb7cdaf07/100173723.png"],
    placeholder: "🌾",
    weight: "400 g",
    rating: 4.6,
    reviews: 54,
    badge: "REA",
    description: "Exklusivt torrfoder med vildsvin och renkött — smaker din katt aldrig ätit förut. Spannmålsfritt och rikt på protein från vilt kött. En riktig delikatess för din kräsne katt.",
    tags: ["spannmålsfritt", "vilt", "exklusivt"],
    inStock: true,
    sku: "CL-WR-400",
  },
  {
    id: 7,
    slug: "acana-pacifica-cat-340g",
    name: "Acana Pacifica Cat & Kitten 340g",
    brand: "Acana",
    category: "torrfoder",
    price: 159,
    originalPrice: null,
    image: null,
    images: [],
    placeholder: "🌾",
    weight: "340 g",
    rating: 4.9,
    reviews: 183,
    badge: "Premium",
    description: "Acana Pacifica innehåller hela sardiner, sill och torsk — fiskar fångade i havet. Biologiskt anpassat foder med 75% fisk och 25% frukt, grönsaker & botaniska ingredienser. Utan spannmål.",
    tags: ["spannmålsfritt", "fisk", "biologiskt anpassat"],
    inStock: true,
    sku: "AC-PAC-340",
  },
  {
    id: 8,
    slug: "acana-pacifica-cat-1-8kg",
    name: "Acana Pacifica Cat & Kitten 1,8 kg",
    brand: "Acana",
    category: "torrfoder",
    price: 549,
    originalPrice: null,
    image: null,
    images: [],
    placeholder: "🌾",
    weight: "1,8 kg",
    rating: 4.9,
    reviews: 76,
    badge: null,
    description: "Acana Pacifica innehåller hela sardiner, sill och torsk — fiskar fångade i havet. Biologiskt anpassat foder med 75% fisk och 25% frukt, grönsaker & botaniska ingredienser. Utan spannmål.",
    tags: ["spannmålsfritt", "fisk", "biologiskt anpassat"],
    inStock: true,
    sku: "AC-PAC-1800",
  },
  {
    id: 9,
    slug: "acana-prairie-cat-340g",
    name: "Acana Wild Prairie Cat 340g",
    brand: "Acana",
    category: "torrfoder",
    price: 159,
    originalPrice: null,
    image: null,
    images: [],
    placeholder: "🌾",
    weight: "340 g",
    rating: 4.8,
    reviews: 142,
    badge: "Populär",
    description: "Acana Wild Prairie är gjord på fri-räckvidd kyckling, kalkon och ägg. 75% kött och fisk, 25% frukt och grönsaker — utan spannmål. Rik näringsprofil för en stark och hälsosam katt.",
    tags: ["spannmålsfritt", "kyckling", "fri-räckvidd"],
    inStock: true,
    sku: "AC-WP-340",
  },
  {
    id: 10,
    slug: "acana-prairie-cat-1-8kg",
    name: "Acana Wild Prairie Cat 1,8 kg",
    brand: "Acana",
    category: "torrfoder",
    price: 549,
    originalPrice: null,
    image: null,
    images: [],
    placeholder: "🌾",
    weight: "1,8 kg",
    rating: 4.8,
    reviews: 65,
    badge: null,
    description: "Acana Wild Prairie är gjord på fri-räckvidd kyckling, kalkon och ägg. 75% kött och fisk, 25% frukt och grönsaker — utan spannmål. Rik näringsprofil för en stark och hälsosam katt.",
    tags: ["spannmålsfritt", "kyckling", "fri-räckvidd"],
    inStock: true,
    sku: "AC-WP-1800",
  },
  {
    id: 11,
    slug: "calibra-life-adult-lax-1-5kg",
    name: "Calibra Life Adult Lax 1,5 kg",
    brand: "Calibra",
    category: "torrfoder",
    price: 149,
    originalPrice: null,
    image: null,
    images: [],
    placeholder: "🌾",
    weight: "1,5 kg",
    rating: 4.5,
    reviews: 117,
    badge: null,
    description: "Calibra Life Adult med lax är ett komplett torrfoder för vuxna katter. Formulerat med Calibra Life-teknologin för optimal matsmältning och en skin & pälshälsa. Utan spannmål.",
    tags: ["spannmålsfritt", "lax", "vuxen katt"],
    inStock: true,
    sku: "CA-LA-1500",
  },
  {
    id: 12,
    slug: "calibra-life-kitten-kyckling-1-5kg",
    name: "Calibra Life Kitten Kyckling 1,5 kg",
    brand: "Calibra",
    category: "torrfoder",
    price: 159,
    originalPrice: null,
    image: null,
    images: [],
    placeholder: "🌾",
    weight: "1,5 kg",
    rating: 4.6,
    reviews: 88,
    badge: "Kattunge",
    description: "Speciellt formulerat för kattungar upp till 12 månader. Calibra Life Kitten innehåller hög andel kyckling, DHA för hjärnutveckling och kolostrum för immunförsvar.",
    tags: ["kattunge", "kyckling", "DHA"],
    inStock: true,
    sku: "CA-KI-1500",
  },
  {
    id: 13,
    slug: "calibra-life-adult-kyckling-6kg",
    name: "Calibra Life Adult Kyckling 6 kg",
    brand: "Calibra",
    category: "torrfoder",
    price: 449,
    originalPrice: 499,
    image: null,
    images: [],
    placeholder: "🌾",
    weight: "6 kg",
    rating: 4.5,
    reviews: 53,
    badge: "Spara mer",
    description: "Storpack för den sparsamme kattvännen. Calibra Life Adult Kyckling är ett komplett och balanserat foder för vuxna katter med kyckling som primär proteinkälla.",
    tags: ["spannmålsfritt", "kyckling", "storpack"],
    inStock: true,
    sku: "CA-AK-6000",
  },

  // ── VÅTFODER ──────────────────────────────────────────────
  {
    id: 14,
    slug: "carnilove-pate-fjadarfa-85g",
    name: "Carnilove Paté med Fjäderfä 85g",
    brand: "Carnilove",
    category: "vatfoder",
    price: 29,
    originalPrice: null,
    image: "https://images.ctfassets.net/wxpwprc19ca5/4ajGkWygcSFXFISPPvATEn/9f2c33064f8578db7416a94cb13d27a4/104101378.png",
    images: ["https://images.ctfassets.net/wxpwprc19ca5/4ajGkWygcSFXFISPPvATEn/9f2c33064f8578db7416a94cb13d27a4/104101378.png"],
    placeholder: "🍖",
    weight: "85 g",
    rating: 4.7,
    reviews: 203,
    badge: null,
    description: "Len och smakrik paté med fjäderfä. 100% naturliga ingredienser, utan tillsatta sockerarter och konserveringsmedel. Högt köttinnehåll som katter älskar.",
    tags: ["paté", "fjäderfä", "naturlig"],
    inStock: true,
    sku: "CL-WP-POULTRY",
  },
  {
    id: 15,
    slug: "carnilove-pate-lax-85g",
    name: "Carnilove Paté med Lax 85g",
    brand: "Carnilove",
    category: "vatfoder",
    price: 29,
    originalPrice: null,
    image: "https://images.ctfassets.net/wxpwprc19ca5/4o67Hvq1cbN0w5lS3k0YpE/f4d074c270ceb3b8d9e3bd3b75cfe7d8/104101372.png",
    images: ["https://images.ctfassets.net/wxpwprc19ca5/4o67Hvq1cbN0w5lS3k0YpE/f4d074c270ceb3b8d9e3bd3b75cfe7d8/104101372.png"],
    placeholder: "🍖",
    weight: "85 g",
    rating: 4.8,
    reviews: 178,
    badge: "Populär",
    description: "Delikat paté med norsk lax. Rik på omega-3 fettsyror för en blank och fin päls. Spannmålsfritt och utan konstgjorda tillsatser.",
    tags: ["paté", "lax", "omega-3"],
    inStock: true,
    sku: "CL-WP-SALMON",
  },
  {
    id: 16,
    slug: "carnilove-pate-vildsvin-85g",
    name: "Carnilove Paté med Vildsvin 85g",
    brand: "Carnilove",
    category: "vatfoder",
    price: 32,
    originalPrice: null,
    image: "https://images.ctfassets.net/wxpwprc19ca5/4GxI1sqFo5aNYJQxcKVYMf/ccfd2a88b0b4ef0385827142b93f8186/104101374.png",
    images: ["https://images.ctfassets.net/wxpwprc19ca5/4GxI1sqFo5aNYJQxcKVYMf/ccfd2a88b0b4ef0385827142b93f8186/104101374.png"],
    placeholder: "🍖",
    weight: "85 g",
    rating: 4.6,
    reviews: 94,
    badge: null,
    description: "Exklusiv paté med vildsvin — ett sällsynt och smakrikt kött från europeisk skog. Högt proteininnehåll, spannmålsfritt och 100% naturlig.",
    tags: ["paté", "vilt", "exklusivt"],
    inStock: true,
    sku: "CL-WP-BOAR",
  },
  {
    id: 17,
    slug: "carnilove-pate-kanin-85g",
    name: "Carnilove Paté med Kanin 85g",
    brand: "Carnilove",
    category: "vatfoder",
    price: 32,
    originalPrice: null,
    image: "https://images.ctfassets.net/wxpwprc19ca5/1UmLXotPclZaYYPTt1TIYc/4c9b2dcaaa744b7d09efd393625ea36e/104101376.png",
    images: ["https://images.ctfassets.net/wxpwprc19ca5/1UmLXotPclZaYYPTt1TIYc/4c9b2dcaaa744b7d09efd393625ea36e/104101376.png"],
    placeholder: "🍖",
    weight: "85 g",
    rating: 4.7,
    reviews: 112,
    badge: "Nyhet",
    description: "Len paté på kaninkött — en naturlig bytesdjurskälla som katter instinktivt föredrar. Utan spannmål, perfekt för katter med känslig matsmältning.",
    tags: ["paté", "kanin", "känslig mage"],
    inStock: true,
    sku: "CL-WP-RABBIT",
  },
  {
    id: 18,
    slug: "calibra-konserv-lax-100g",
    name: "Calibra Life Adult Lax konserv 100g",
    brand: "Calibra",
    category: "vatfoder",
    price: 19,
    originalPrice: null,
    image: null,
    images: [],
    placeholder: "🍖",
    weight: "100 g",
    rating: 4.4,
    reviews: 87,
    badge: null,
    description: "Komplett och balanserat våtfoder med lax för vuxna katter. Rik på naturliga proteiner och omega-fettsyror. Utan spannmål och konstgjorda tillsatser.",
    tags: ["konserv", "lax", "vuxen katt"],
    inStock: true,
    sku: "CA-LA-100",
  },
  {
    id: 19,
    slug: "calibra-konserv-kyckling-100g",
    name: "Calibra Life Adult Kyckling konserv 100g",
    brand: "Calibra",
    category: "vatfoder",
    price: 19,
    originalPrice: null,
    image: null,
    images: [],
    placeholder: "🍖",
    weight: "100 g",
    rating: 4.4,
    reviews: 73,
    badge: null,
    description: "Komplett och balanserat våtfoder med kyckling för vuxna katter. Lätt smältbart och välsmakande. Utan spannmål och konstgjorda tillsatser.",
    tags: ["konserv", "kyckling", "vuxen katt"],
    inStock: true,
    sku: "CA-AK-100",
  },

  // ── SNACKS ────────────────────────────────────────────────
  {
    id: 20,
    slug: "carnilove-semi-moist-lax-oring-200g",
    name: "Carnilove Semi-Moist Snack Lax & Öring 200g",
    brand: "Carnilove",
    category: "snacks",
    price: 89,
    originalPrice: null,
    image: "https://images.ctfassets.net/wxpwprc19ca5/5OxDsaYiYFWrGPBr02KGee/6abeac747062751ea7d311c14c2bf670/103100792.png",
    images: ["https://images.ctfassets.net/wxpwprc19ca5/5OxDsaYiYFWrGPBr02KGee/6abeac747062751ea7d311c14c2bf670/103100792.png"],
    placeholder: "🎁",
    weight: "200 g",
    rating: 4.9,
    reviews: 267,
    badge: "Favorit",
    description: "Mjuka godsaker med lax och öring. Spannmålsfria, utan artificiella färgämnen. Perfekta som belöning vid träning eller som extra kärlek. Katter är galna i dem!",
    tags: ["snacks", "lax", "mjuka"],
    inStock: true,
    sku: "CL-SM-ST",
  },
  {
    id: 21,
    slug: "carnilove-semi-moist-kyckling-vildfagel-200g",
    name: "Carnilove Semi-Moist Snack Kyckling & Viltfågel 200g",
    brand: "Carnilove",
    category: "snacks",
    price: 89,
    originalPrice: null,
    image: "https://images.ctfassets.net/wxpwprc19ca5/5DKpGXCRT6Rc020dRHxTii/910ae4c5c5001e62e06bfb0c5a71695d/101112415.png",
    images: ["https://images.ctfassets.net/wxpwprc19ca5/5DKpGXCRT6Rc020dRHxTii/910ae4c5c5001e62e06bfb0c5a71695d/101112415.png"],
    placeholder: "🎁",
    weight: "200 g",
    rating: 4.8,
    reviews: 189,
    badge: null,
    description: "Spannmålsfria mjuka snacks med kyckling och viltfågel. Naturliga ingredienser, rikt på protein. Perfekta som träningsbelöning eller extra godsak.",
    tags: ["snacks", "kyckling", "viltfågel"],
    inStock: true,
    sku: "CL-SM-CG",
  },
  {
    id: 22,
    slug: "carnilove-semi-moist-norkott-hjort-200g",
    name: "Carnilove Semi-Moist Snack Nötkött & Hjort 200g",
    brand: "Carnilove",
    category: "snacks",
    price: 89,
    originalPrice: null,
    image: "https://images.ctfassets.net/wxpwprc19ca5/6dpQeqNKYAVM3CxcEcwlsN/ba46b248e525125634ce34c0163df000/103100794.png",
    images: ["https://images.ctfassets.net/wxpwprc19ca5/6dpQeqNKYAVM3CxcEcwlsN/ba46b248e525125634ce34c0163df000/103100794.png"],
    placeholder: "🎁",
    weight: "200 g",
    rating: 4.7,
    reviews: 134,
    badge: null,
    description: "Exklusiva mjuka snacks med nötkött och hjort. Lågglykemisk, spannmålsfri formel. Perfekta för katter som föredrar smak av vilt.",
    tags: ["snacks", "nötkött", "hjort"],
    inStock: true,
    sku: "CL-SM-BD",
  },
  {
    id: 23,
    slug: "carnilove-frystorkad-lax-40g",
    name: "Carnilove Frystorkad Snack Lax 40g",
    brand: "Carnilove",
    category: "snacks",
    price: 99,
    originalPrice: null,
    image: "https://images.ctfassets.net/wxpwprc19ca5/2PZ8jG427YqKgZzw5iY7t2/c85b1f6721c77488d46a3b1d76295944/101112437.png",
    images: ["https://images.ctfassets.net/wxpwprc19ca5/2PZ8jG427YqKgZzw5iY7t2/c85b1f6721c77488d46a3b1d76295944/101112437.png"],
    placeholder: "🎁",
    weight: "40 g",
    rating: 4.9,
    reviews: 321,
    badge: "100% naturlig",
    description: "Ren frystorkad lax — inga tillsatser, inga fyllnadsmedel. Bara lax. Frystorkning bevarar alla naturliga näringsamnen och smaker. En äkta delikatess för din katt.",
    tags: ["frystorkad", "lax", "naturlig"],
    inStock: true,
    sku: "CL-FD-SALMON",
  },
  {
    id: 24,
    slug: "carnilove-frystorkad-kanin-40g",
    name: "Carnilove Frystorkad Snack Kanin 40g",
    brand: "Carnilove",
    category: "snacks",
    price: 99,
    originalPrice: null,
    image: "https://images.ctfassets.net/wxpwprc19ca5/3c7mxI6rvpDeQx16pE8RO8/c1371e4d2bc9133bec1a3764fe06e810/101112438.png",
    images: ["https://images.ctfassets.net/wxpwprc19ca5/3c7mxI6rvpDeQx16pE8RO8/c1371e4d2bc9133bec1a3764fe06e810/101112438.png"],
    placeholder: "🎁",
    weight: "40 g",
    rating: 4.8,
    reviews: 198,
    badge: null,
    description: "Ren frystorkad kanin — ett av kattens naturliga bytesdjur. Utan tillsatser. Frystorkning bevarar alla näringsamnen och den intensiva smaken som katter älskar.",
    tags: ["frystorkad", "kanin", "naturlig"],
    inStock: true,
    sku: "CL-FD-RABBIT",
  },

  // ── LEKSAKER ──────────────────────────────────────────────
  {
    id: 25,
    slug: "trixie-activity-fun-board",
    name: "Trixie Cat Activity Fun Board 5-i-1",
    brand: "Trixie",
    category: "leksaker",
    price: 249,
    originalPrice: null,
    image: "https://cdn.trixie.de/assets/img/280x280/PHO_PRO_CLIP_4590-3_%23SALL_%23AWK_%23V1.jpg",
    images: ["https://cdn.trixie.de/assets/img/280x280/PHO_PRO_CLIP_4590-3_%23SALL_%23AWK_%23V1.jpg"],
    placeholder: "🐾",
    weight: null,
    rating: 4.7,
    reviews: 312,
    badge: "Bästsäljare",
    description: "5 interaktiva stationer i ett bräde — bollar, mjuka tappar, konor, tråg och peggboard. Stimulerar din katts naturliga jaktsinstinkt och håller den mentalt aktiv. Passar alla katter.",
    tags: ["interaktiv", "aktivering", "mental stimulering"],
    inStock: true,
    sku: "TX-AFB-5IN1",
  },
  {
    id: 26,
    slug: "trixie-fjaderspö-teleskop",
    name: "Trixie Fjäderspö med Teleskopstång",
    brand: "Trixie",
    category: "leksaker",
    price: 79,
    originalPrice: null,
    image: "https://cdn.trixie.de/assets/img/280x280/PHO_PRO_CLIP_4567-1_%23SALL_%23AWK_%23V1.jpg",
    images: ["https://cdn.trixie.de/assets/img/280x280/PHO_PRO_CLIP_4567-1_%23SALL_%23AWK_%23V1.jpg"],
    placeholder: "🐾",
    weight: null,
    rating: 4.6,
    reviews: 445,
    badge: "Populär",
    description: "Klassiskt fjäderspö med utdragbar stång. Skapar rörliga fjädringsmönster som väcker kattens jaktsinstinkt. Lång stång = säkert avstånd för handen.",
    tags: ["fjäderspö", "interaktiv", "jaktinstinkt"],
    inStock: true,
    sku: "TX-FT-TEL",
  },
  {
    id: 27,
    slug: "trixie-plyschmys-kattnip",
    name: "Trixie Plyschmöss med Kattmynta 4-pack",
    brand: "Trixie",
    category: "leksaker",
    price: 69,
    originalPrice: null,
    image: null,
    images: [],
    placeholder: "🐾",
    weight: null,
    rating: 4.5,
    reviews: 289,
    badge: null,
    description: "Fyra realistiska plyschmöss fyllda med kattmynta. Kattmyntan lockar de flesta katter till lek och aktivitet. Mjukt material, säkert för katter.",
    tags: ["kattmynta", "plyschleksak", "4-pack"],
    inStock: true,
    sku: "TX-PM-NIP4",
  },
  {
    id: 28,
    slug: "trixie-bolltunnel",
    name: "Trixie 3-Vägs Bolltunnel med Boll",
    brand: "Trixie",
    category: "leksaker",
    price: 149,
    originalPrice: null,
    image: null,
    images: [],
    placeholder: "🐾",
    weight: null,
    rating: 4.4,
    reviews: 178,
    badge: null,
    description: "3-vägs crinkle-tunnel med en inbyggd boll som rör sig. Katterna älskar att klättra in och vänta på bytet. Vikbar och lätt att förvara.",
    tags: ["tunnel", "crinkle", "interaktiv"],
    inStock: true,
    sku: "TX-TUN-3WAY",
  },
  {
    id: 29,
    slug: "trixie-laser-pointer",
    name: "Trixie Laser Pointer Kattleksak",
    brand: "Trixie",
    category: "leksaker",
    price: 89,
    originalPrice: null,
    image: null,
    images: [],
    placeholder: "🐾",
    weight: null,
    rating: 4.6,
    reviews: 534,
    badge: "Favorit",
    description: "Laserpointer med byte-mode och automatisk tidsinställning. Håller katten aktiv och i rörelse. Inkl. batteri. Säker för katter — lys aldrig direkt i ögonen.",
    tags: ["laser", "automatisk", "rörelse"],
    inStock: true,
    sku: "TX-LASER-1",
  },

  // ── KATTTRÄD & MÖBLER ────────────────────────────────────
  {
    id: 30,
    slug: "trixie-badalona-katttra-142cm",
    name: "Trixie Badalona Kattträd 142 cm",
    brand: "Trixie",
    category: "mobler",
    price: 899,
    originalPrice: null,
    image: "https://cdn.trixie.de/assets/img/280x280/PHO_PRO_CAT_CLIP_62631-1_%23SALL_%23AWK_%23V1.jpg",
    images: ["https://cdn.trixie.de/assets/img/280x280/PHO_PRO_CAT_CLIP_62631-1_%23SALL_%23AWK_%23V1.jpg"],
    placeholder: "🌳",
    weight: null,
    rating: 4.6,
    reviews: 187,
    badge: "Populär",
    description: "Stort kattträd med flera plattformar, hammock och sisal-repstammar. 142 cm högt med bred stabil bas. Perfekt för aktiva katter som gillar att klättra och observera. Grå och beige design.",
    tags: ["kattträd", "klättring", "sisal"],
    inStock: true,
    sku: "TX-BAD-142",
  },
  {
    id: 31,
    slug: "trixie-mijas-katttra-87cm",
    name: "Trixie Mijas Kattträd 87 cm",
    brand: "Trixie",
    category: "mobler",
    price: 499,
    originalPrice: null,
    image: "https://cdn.trixie.de/assets/img/280x280/PHO_PRO_CAT_CLIP_44545-1_%23SALL_%23AWK_%23V1.jpg",
    images: ["https://cdn.trixie.de/assets/img/280x280/PHO_PRO_CAT_CLIP_44545-1_%23SALL_%23AWK_%23V1.jpg"],
    placeholder: "🌳",
    weight: null,
    rating: 4.5,
    reviews: 134,
    badge: null,
    description: "Kompakt kattträd 87 cm med klösbräda, lekplattform och hängande leksak. Passar lägenheten och ensamkatter. Sisal-rep och mjuka kuddar ingår.",
    tags: ["kattträd", "kompakt", "klösbräda"],
    inStock: true,
    sku: "TX-MIJ-87",
  },
  {
    id: 32,
    slug: "trixie-klossbreda-sisal-60cm",
    name: "Trixie Klösbräda Sisal 60 cm",
    brand: "Trixie",
    category: "mobler",
    price: 179,
    originalPrice: null,
    image: null,
    images: [],
    placeholder: "🌳",
    weight: null,
    rating: 4.4,
    reviews: 256,
    badge: null,
    description: "Enkel och stabil klösbräda klädd i sisal. Monteras på väggen med medföljande beslag. 60 cm lång — ger katten det klösande den behöver och skyddar möblerna.",
    tags: ["klösbräda", "sisal", "väggmonterad"],
    inStock: true,
    sku: "TX-SCR-60",
  },
  {
    id: 33,
    slug: "trixie-hammock-radiatorkorg",
    name: "Trixie Hammock Radiatorkorg",
    brand: "Trixie",
    category: "mobler",
    price: 299,
    originalPrice: null,
    image: "https://cdn.trixie.de/assets/img/280x280/PHO_PRO_CLIP_43204-1_%23SALL_%23AWK_%23V1.jpg",
    images: ["https://cdn.trixie.de/assets/img/280x280/PHO_PRO_CLIP_43204-1_%23SALL_%23AWK_%23V1.jpg"],
    placeholder: "🌳",
    weight: null,
    rating: 4.7,
    reviews: 312,
    badge: "Favorit",
    description: "Hängbädd som fästs på radiatorn med enkla krokar. Ger katten den varma, upphöjda sovskötseln den älskar. Bärighet upp till 5 kg. Maskintvättbart täcke.",
    tags: ["radiator", "hammock", "maskintvättbar"],
    inStock: true,
    sku: "TX-HAM-RAD",
  },

  // ── BÄDDAR & KORGAR ───────────────────────────────────────
  {
    id: 34,
    slug: "trixie-cuddly-cave-bed",
    name: "Trixie Cuddly Cave Kattsäng",
    brand: "Trixie",
    category: "baddar",
    price: 299,
    originalPrice: null,
    image: "https://cdn.trixie.de/assets/img/280x280/PHO_PRO_CLIP_36290-1_%23SALL_%23AWK_%23V1.jpg",
    images: ["https://cdn.trixie.de/assets/img/280x280/PHO_PRO_CLIP_36290-1_%23SALL_%23AWK_%23V1.jpg"],
    placeholder: "😴",
    weight: null,
    rating: 4.8,
    reviews: 421,
    badge: "Bästsäljare",
    description: "Mysig grotta-liknande säng i plysch. Katter som gillar att gömma sig och känna sig trygga älskar den. Avtagbar och tvättbar kudde. Fler storlekar finns.",
    tags: ["grotta", "plysch", "tvättbar"],
    inStock: true,
    sku: "TX-CC-BED",
  },
  {
    id: 35,
    slug: "trixie-cozy-cushion-70x50",
    name: "Trixie Cozy Kudde 70×50 cm",
    brand: "Trixie",
    category: "baddar",
    price: 199,
    originalPrice: null,
    image: "https://cdn.trixie.de/assets/img/280x280/PHO_PRO_CLIP_36281-1_%23SALL_%23AWK_%23V1.jpg",
    images: ["https://cdn.trixie.de/assets/img/280x280/PHO_PRO_CLIP_36281-1_%23SALL_%23AWK_%23V1.jpg"],
    placeholder: "😴",
    weight: null,
    rating: 4.5,
    reviews: 234,
    badge: null,
    description: "Stor, mjuk kudde i plyschmaterial. 70×50 cm — tillräckligt stor för de flesta katter. Maskintvättbar vid 30°C. Grå färg passar de flesta hem.",
    tags: ["kudde", "plysch", "maskintvättbar"],
    inStock: true,
    sku: "TX-COZ-7050",
  },
  {
    id: 36,
    slug: "trixie-heated-cat-mat",
    name: "Trixie Värme-Matta för Katt 45×36 cm",
    brand: "Trixie",
    category: "baddar",
    price: 349,
    originalPrice: null,
    image: null,
    images: [],
    placeholder: "😴",
    weight: null,
    rating: 4.7,
    reviews: 167,
    badge: "Nyhet",
    description: "Självuppvärmande matta utan el som absorberar kattens egen kropsvärme och reflekterar den tillbaka. Perfekt för vintrar och äldre katter med ledproblem.",
    tags: ["värmematta", "självuppvärmande", "äldre katt"],
    inStock: true,
    sku: "TX-HM-4536",
  },

  // ── SKÅLAR & FONTÄNER ─────────────────────────────────────
  {
    id: 37,
    slug: "trixie-keramikskalar-set",
    name: "Trixie Keramikskål 0,3 L",
    brand: "Trixie",
    category: "skalar",
    price: 79,
    originalPrice: null,
    image: null,
    images: [],
    placeholder: "🥣",
    weight: null,
    rating: 4.5,
    reviews: 198,
    badge: null,
    description: "Robust keramikskål 0,3 L — hygienisk, lätt att rengöra och diskmaskinssäker. Halkfri botten. Passar katter i alla åldrar. Klassisk vit design.",
    tags: ["keramik", "diskmaskinssäker", "halkfri"],
    inStock: true,
    sku: "TX-CER-03",
  },
  {
    id: 38,
    slug: "trixie-vattenfontän-3-8l",
    name: "Trixie Vattenfontän 3,8 L",
    brand: "Trixie",
    category: "skalar",
    price: 449,
    originalPrice: null,
    image: "https://cdn.trixie.de/assets/img/280x280/PHO_PRO_CLIP_24446-1_%23SALL_%23AWK_%23V1.jpg",
    images: ["https://cdn.trixie.de/assets/img/280x280/PHO_PRO_CLIP_24446-1_%23SALL_%23AWK_%23V1.jpg"],
    placeholder: "🥣",
    weight: null,
    rating: 4.8,
    reviews: 345,
    badge: "Favorit",
    description: "Cirkulerande vattenfontän 3,8 L med kolfilter och tre flödesinställningar. Katter dricker mer när vattnet rör sig — minskar risken för urinvägsproblem. Tyst motor. BPA-fri plast.",
    tags: ["fontän", "filter", "kolfilter"],
    inStock: true,
    sku: "TX-FONT-38",
  },
  {
    id: 39,
    slug: "trixie-upphojd-skalbradda",
    name: "Trixie Upphöjt Skålbräde med 2 Skålar",
    brand: "Trixie",
    category: "skalar",
    price: 199,
    originalPrice: null,
    image: null,
    images: [],
    placeholder: "🥣",
    weight: null,
    rating: 4.6,
    reviews: 143,
    badge: null,
    description: "Upphöjt träbräde med två keramiskålar 0,3 L. Bättre ätposition minskar stress på nacke och matsmältningsproblem. Värmlig trä-design i bamboo.",
    tags: ["upphöjt", "ergonomisk", "bamboo"],
    inStock: true,
    sku: "TX-STAND-2",
  },

  // ── TOALETT & SAND ────────────────────────────────────────
  {
    id: 40,
    slug: "cats-best-smart-pellets-10l",
    name: "Cat's Best Smart Pellets 10 L",
    brand: "Cat's Best",
    category: "sand",
    price: 189,
    originalPrice: null,
    image: null,
    images: [],
    placeholder: "🪨",
    weight: "10 L",
    rating: 4.7,
    reviews: 456,
    badge: "Bästsäljare",
    description: "Ekologisk kattsand av träfibrer. Extremt hög absorptionsförmåga — 700% sin egen vikt i vätska. Neutraliserar lukter naturligt utan parfym. Spolbar i toaletten (kolla lokala regler). 10 L räcker länge.",
    tags: ["ekologisk", "träfiber", "luktfri"],
    inStock: true,
    sku: "CB-SP-10L",
  },
  {
    id: 41,
    slug: "cats-best-nature-gold-10l",
    name: "Cat's Best Nature Gold 10 L",
    brand: "Cat's Best",
    category: "sand",
    price: 219,
    originalPrice: null,
    image: null,
    images: [],
    placeholder: "🪨",
    weight: "10 L",
    rating: 4.8,
    reviews: 312,
    badge: "Premium",
    description: "Premiumversion med ännu bättre klumpbildning och luckosuppression. Baserad på träfibrer med naturliga eteriska oljor. Dammfri, lätt att rengöra. Utmärkt för känsliga katter.",
    tags: ["premium", "träfiber", "dammfri"],
    inStock: true,
    sku: "CB-NG-10L",
  },
  {
    id: 42,
    slug: "trixie-kattlada-med-lock",
    name: "Trixie Kattlåda med Lock 56×40×40 cm",
    brand: "Trixie",
    category: "sand",
    price: 299,
    originalPrice: null,
    image: null,
    images: [],
    placeholder: "🪨",
    weight: null,
    rating: 4.5,
    reviews: 167,
    badge: null,
    description: "Klassisk kattlåda med lock och skyfflucka. 56×40×40 cm ger god rörelsefrihet. Luckan håller sanden inne och minskar luktutsläpp. Lätt att rengöra, BPA-fri plast.",
    tags: ["kattlåda", "lock", "BPA-fri"],
    inStock: true,
    sku: "TX-BOX-LID",
  },
];

export function getProduct(slug) {
  return products.find(p => p.slug === slug) ?? null;
}
